# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
output: 'interleaved'

tasks:
  ddev:ensure:
    desc: Start ddev if not already running
    dir: ./goformx-laravel
    cmd: ddev describe >/dev/null 2>&1 || ddev start
    silent: true

  dev:
    desc: Start all services (Go sidecar + Laravel via ddev)
    dir: ./goformx-laravel
    deps: [ddev:ensure]
    cmd: ddev composer dev
    interactive: true

  dev:go:
    desc: Start Go backend standalone (without ddev; requires local PostgreSQL)
    dir: ./goforms
    cmd: task dev:backend

  dev:laravel:
    desc: Start Laravel via ddev (includes Go sidecar)
    dir: ./goformx-laravel
    deps: [ddev:ensure]
    cmd: ddev composer dev
    interactive: true

  install:
    desc: Install dependencies for both services
    cmds:
      - task: install:go
      - task: install:laravel

  install:go:
    desc: Install Go dependencies and tools
    dir: ./goforms
    cmd: task install

  install:laravel:
    desc: Install PHP and Node dependencies via ddev (creates .env, generates key)
    dir: ./goformx-laravel
    cmds:
      - ddev composer setup

  test:
    desc: Run all test suites
    deps: [test:go, test:laravel]

  test:go:
    desc: Run Go unit tests
    dir: ./goforms
    cmd: task test:backend

  test:laravel:
    desc: Run Laravel Pest tests
    dir: ./goformx-laravel
    cmd: php artisan test --compact

  lint:
    desc: Run all linters
    deps: [lint:go, lint:laravel]

  lint:go:
    desc: Run Go linters (fmt, vet, golangci-lint)
    dir: ./goforms
    cmd: task lint:backend

  lint:laravel:
    desc: Run PHP and frontend linters
    dir: ./goformx-laravel
    cmds:
      - vendor/bin/pint --dirty --format agent
      - npm run lint

  test:e2e:
    desc: Seed DB and run Playwright E2E tests
    dir: ./goformx-laravel
    deps: [ddev:ensure]
    cmds:
      - ddev exec php artisan migrate:fresh --seed --seeder=E2eTestSeeder --no-interaction
      - npx playwright test

  test:e2e:ui:
    desc: Seed DB and run Playwright E2E tests in UI mode
    dir: ./goformx-laravel
    deps: [ddev:ensure]
    cmds:
      - ddev exec php artisan migrate:fresh --seed --seeder=E2eTestSeeder --no-interaction
      - npx playwright test --ui

  setup:
    desc: Full first-time setup (ddev, Go tools, deps, generate, migrate)
    cmds:
      - task: setup:ddev:start
      - task: install:go
      - task: install:laravel
      - task: setup:go:generate
      - task: setup:go:migrate

  setup:ddev:start:
    desc: Start ddev environment (provides postgres and goforms container)
    cmds:
      - task: ddev:ensure

  setup:go:generate:
    desc: Generate Go code artifacts
    dir: ./goforms
    cmd: task generate

  setup:go:migrate:
    desc: Apply Go database migrations inside ddev goforms container
    dir: ./goformx-laravel
    cmd: ddev exec -s goforms task migrate:up DB_HOST=goforms-db DB_NAME=goforms DB_USERNAME=goforms DB_PASSWORD=goforms
