// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -typed -source=event.go -destination=../../../../test/mocks/events/mock_eventbus.go -package=events
//

// Package events is a generated GoMock package.
package events

import (
	context "context"
	reflect "reflect"
	time "time"

	events "github.com/goformx/goforms/internal/domain/common/events"
	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// Metadata mocks base method.
func (m *MockEvent) Metadata() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockEventMockRecorder) Metadata() *MockEventMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockEvent)(nil).Metadata))
	return &MockEventMetadataCall{Call: call}
}

// MockEventMetadataCall wrap *gomock.Call
type MockEventMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventMetadataCall) Return(arg0 map[string]any) *MockEventMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventMetadataCall) Do(f func() map[string]any) *MockEventMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventMetadataCall) DoAndReturn(f func() map[string]any) *MockEventMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockEvent) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockEventMockRecorder) Name() *MockEventNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockEvent)(nil).Name))
	return &MockEventNameCall{Call: call}
}

// MockEventNameCall wrap *gomock.Call
type MockEventNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventNameCall) Return(arg0 string) *MockEventNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventNameCall) Do(f func() string) *MockEventNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventNameCall) DoAndReturn(f func() string) *MockEventNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Payload mocks base method.
func (m *MockEvent) Payload() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].(any)
	return ret0
}

// Payload indicates an expected call of Payload.
func (mr *MockEventMockRecorder) Payload() *MockEventPayloadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockEvent)(nil).Payload))
	return &MockEventPayloadCall{Call: call}
}

// MockEventPayloadCall wrap *gomock.Call
type MockEventPayloadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventPayloadCall) Return(arg0 any) *MockEventPayloadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventPayloadCall) Do(f func() any) *MockEventPayloadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventPayloadCall) DoAndReturn(f func() any) *MockEventPayloadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Timestamp mocks base method.
func (m *MockEvent) Timestamp() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timestamp")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Timestamp indicates an expected call of Timestamp.
func (mr *MockEventMockRecorder) Timestamp() *MockEventTimestampCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timestamp", reflect.TypeOf((*MockEvent)(nil).Timestamp))
	return &MockEventTimestampCall{Call: call}
}

// MockEventTimestampCall wrap *gomock.Call
type MockEventTimestampCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventTimestampCall) Return(arg0 time.Time) *MockEventTimestampCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventTimestampCall) Do(f func() time.Time) *MockEventTimestampCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventTimestampCall) DoAndReturn(f func() time.Time) *MockEventTimestampCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(ctx context.Context, event events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(ctx, event any) *MockPublisherPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), ctx, event)
	return &MockPublisherPublishCall{Call: call}
}

// MockPublisherPublishCall wrap *gomock.Call
type MockPublisherPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublisherPublishCall) Return(arg0 error) *MockPublisherPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublisherPublishCall) Do(f func(context.Context, events.Event) error) *MockPublisherPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublisherPublishCall) DoAndReturn(f func(context.Context, events.Event) error) *MockPublisherPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishBatch mocks base method.
func (m *MockPublisher) PublishBatch(ctx context.Context, arg1 []events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBatch", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBatch indicates an expected call of PublishBatch.
func (mr *MockPublisherMockRecorder) PublishBatch(ctx, arg1 any) *MockPublisherPublishBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatch", reflect.TypeOf((*MockPublisher)(nil).PublishBatch), ctx, arg1)
	return &MockPublisherPublishBatchCall{Call: call}
}

// MockPublisherPublishBatchCall wrap *gomock.Call
type MockPublisherPublishBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublisherPublishBatchCall) Return(arg0 error) *MockPublisherPublishBatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublisherPublishBatchCall) Do(f func(context.Context, []events.Event) error) *MockPublisherPublishBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublisherPublishBatchCall) DoAndReturn(f func(context.Context, []events.Event) error) *MockPublisherPublishBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	mock := &MockSubscriber{ctrl: ctrl}
	mock.recorder = &MockSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockSubscriber) Subscribe(ctx context.Context, eventName string, handler func(context.Context, events.Event) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, eventName, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSubscriberMockRecorder) Subscribe(ctx, eventName, handler any) *MockSubscriberSubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSubscriber)(nil).Subscribe), ctx, eventName, handler)
	return &MockSubscriberSubscribeCall{Call: call}
}

// MockSubscriberSubscribeCall wrap *gomock.Call
type MockSubscriberSubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberSubscribeCall) Return(arg0 error) *MockSubscriberSubscribeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberSubscribeCall) Do(f func(context.Context, string, func(context.Context, events.Event) error) error) *MockSubscriberSubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberSubscribeCall) DoAndReturn(f func(context.Context, string, func(context.Context, events.Event) error) error) *MockSubscriberSubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Unsubscribe mocks base method.
func (m *MockSubscriber) Unsubscribe(ctx context.Context, eventName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, eventName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubscriberMockRecorder) Unsubscribe(ctx, eventName any) *MockSubscriberUnsubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubscriber)(nil).Unsubscribe), ctx, eventName)
	return &MockSubscriberUnsubscribeCall{Call: call}
}

// MockSubscriberUnsubscribeCall wrap *gomock.Call
type MockSubscriberUnsubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberUnsubscribeCall) Return(arg0 error) *MockSubscriberUnsubscribeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberUnsubscribeCall) Do(f func(context.Context, string) error) *MockSubscriberUnsubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberUnsubscribeCall) DoAndReturn(f func(context.Context, string) error) *MockSubscriberUnsubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
	isgomock struct{}
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockEventHandler) Handle(ctx context.Context, event events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockEventHandlerMockRecorder) Handle(ctx, event any) *MockEventHandlerHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockEventHandler)(nil).Handle), ctx, event)
	return &MockEventHandlerHandleCall{Call: call}
}

// MockEventHandlerHandleCall wrap *gomock.Call
type MockEventHandlerHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventHandlerHandleCall) Return(arg0 error) *MockEventHandlerHandleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventHandlerHandleCall) Do(f func(context.Context, events.Event) error) *MockEventHandlerHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventHandlerHandleCall) DoAndReturn(f func(context.Context, events.Event) error) *MockEventHandlerHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockEventStore) GetByID(ctx context.Context, id string) (events.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(events.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventStoreMockRecorder) GetByID(ctx, id any) *MockEventStoreGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventStore)(nil).GetByID), ctx, id)
	return &MockEventStoreGetByIDCall{Call: call}
}

// MockEventStoreGetByIDCall wrap *gomock.Call
type MockEventStoreGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventStoreGetByIDCall) Return(arg0 events.Event, arg1 error) *MockEventStoreGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventStoreGetByIDCall) Do(f func(context.Context, string) (events.Event, error)) *MockEventStoreGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventStoreGetByIDCall) DoAndReturn(f func(context.Context, string) (events.Event, error)) *MockEventStoreGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByTimeRange mocks base method.
func (m *MockEventStore) GetByTimeRange(ctx context.Context, start, end time.Time) ([]events.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTimeRange", ctx, start, end)
	ret0, _ := ret[0].([]events.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTimeRange indicates an expected call of GetByTimeRange.
func (mr *MockEventStoreMockRecorder) GetByTimeRange(ctx, start, end any) *MockEventStoreGetByTimeRangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTimeRange", reflect.TypeOf((*MockEventStore)(nil).GetByTimeRange), ctx, start, end)
	return &MockEventStoreGetByTimeRangeCall{Call: call}
}

// MockEventStoreGetByTimeRangeCall wrap *gomock.Call
type MockEventStoreGetByTimeRangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventStoreGetByTimeRangeCall) Return(arg0 []events.Event, arg1 error) *MockEventStoreGetByTimeRangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventStoreGetByTimeRangeCall) Do(f func(context.Context, time.Time, time.Time) ([]events.Event, error)) *MockEventStoreGetByTimeRangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventStoreGetByTimeRangeCall) DoAndReturn(f func(context.Context, time.Time, time.Time) ([]events.Event, error)) *MockEventStoreGetByTimeRangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByType mocks base method.
func (m *MockEventStore) GetByType(ctx context.Context, eventType string) ([]events.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByType", ctx, eventType)
	ret0, _ := ret[0].([]events.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByType indicates an expected call of GetByType.
func (mr *MockEventStoreMockRecorder) GetByType(ctx, eventType any) *MockEventStoreGetByTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByType", reflect.TypeOf((*MockEventStore)(nil).GetByType), ctx, eventType)
	return &MockEventStoreGetByTypeCall{Call: call}
}

// MockEventStoreGetByTypeCall wrap *gomock.Call
type MockEventStoreGetByTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventStoreGetByTypeCall) Return(arg0 []events.Event, arg1 error) *MockEventStoreGetByTypeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventStoreGetByTypeCall) Do(f func(context.Context, string) ([]events.Event, error)) *MockEventStoreGetByTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventStoreGetByTypeCall) DoAndReturn(f func(context.Context, string) ([]events.Event, error)) *MockEventStoreGetByTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockEventStore) Save(ctx context.Context, event events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEventStoreMockRecorder) Save(ctx, event any) *MockEventStoreSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEventStore)(nil).Save), ctx, event)
	return &MockEventStoreSaveCall{Call: call}
}

// MockEventStoreSaveCall wrap *gomock.Call
type MockEventStoreSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventStoreSaveCall) Return(arg0 error) *MockEventStoreSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventStoreSaveCall) Do(f func(context.Context, events.Event) error) *MockEventStoreSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventStoreSaveCall) DoAndReturn(f func(context.Context, events.Event) error) *MockEventStoreSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEventBus is a mock of EventBus interface.
type MockEventBus struct {
	ctrl     *gomock.Controller
	recorder *MockEventBusMockRecorder
	isgomock struct{}
}

// MockEventBusMockRecorder is the mock recorder for MockEventBus.
type MockEventBusMockRecorder struct {
	mock *MockEventBus
}

// NewMockEventBus creates a new mock instance.
func NewMockEventBus(ctrl *gomock.Controller) *MockEventBus {
	mock := &MockEventBus{ctrl: ctrl}
	mock.recorder = &MockEventBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBus) EXPECT() *MockEventBusMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockEventBus) Health(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockEventBusMockRecorder) Health(ctx any) *MockEventBusHealthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockEventBus)(nil).Health), ctx)
	return &MockEventBusHealthCall{Call: call}
}

// MockEventBusHealthCall wrap *gomock.Call
type MockEventBusHealthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventBusHealthCall) Return(arg0 error) *MockEventBusHealthCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventBusHealthCall) Do(f func(context.Context) error) *MockEventBusHealthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventBusHealthCall) DoAndReturn(f func(context.Context) error) *MockEventBusHealthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Publish mocks base method.
func (m *MockEventBus) Publish(ctx context.Context, event events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventBusMockRecorder) Publish(ctx, event any) *MockEventBusPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventBus)(nil).Publish), ctx, event)
	return &MockEventBusPublishCall{Call: call}
}

// MockEventBusPublishCall wrap *gomock.Call
type MockEventBusPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventBusPublishCall) Return(arg0 error) *MockEventBusPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventBusPublishCall) Do(f func(context.Context, events.Event) error) *MockEventBusPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventBusPublishCall) DoAndReturn(f func(context.Context, events.Event) error) *MockEventBusPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishBatch mocks base method.
func (m *MockEventBus) PublishBatch(ctx context.Context, arg1 []events.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBatch", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBatch indicates an expected call of PublishBatch.
func (mr *MockEventBusMockRecorder) PublishBatch(ctx, arg1 any) *MockEventBusPublishBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatch", reflect.TypeOf((*MockEventBus)(nil).PublishBatch), ctx, arg1)
	return &MockEventBusPublishBatchCall{Call: call}
}

// MockEventBusPublishBatchCall wrap *gomock.Call
type MockEventBusPublishBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventBusPublishBatchCall) Return(arg0 error) *MockEventBusPublishBatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventBusPublishBatchCall) Do(f func(context.Context, []events.Event) error) *MockEventBusPublishBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventBusPublishBatchCall) DoAndReturn(f func(context.Context, []events.Event) error) *MockEventBusPublishBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockEventBus) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockEventBusMockRecorder) Start(ctx any) *MockEventBusStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEventBus)(nil).Start), ctx)
	return &MockEventBusStartCall{Call: call}
}

// MockEventBusStartCall wrap *gomock.Call
type MockEventBusStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventBusStartCall) Return(arg0 error) *MockEventBusStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventBusStartCall) Do(f func(context.Context) error) *MockEventBusStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventBusStartCall) DoAndReturn(f func(context.Context) error) *MockEventBusStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *MockEventBus) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockEventBusMockRecorder) Stop(ctx any) *MockEventBusStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockEventBus)(nil).Stop), ctx)
	return &MockEventBusStopCall{Call: call}
}

// MockEventBusStopCall wrap *gomock.Call
type MockEventBusStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventBusStopCall) Return(arg0 error) *MockEventBusStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventBusStopCall) Do(f func(context.Context) error) *MockEventBusStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventBusStopCall) DoAndReturn(f func(context.Context) error) *MockEventBusStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Subscribe mocks base method.
func (m *MockEventBus) Subscribe(ctx context.Context, eventName string, handler func(context.Context, events.Event) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, eventName, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventBusMockRecorder) Subscribe(ctx, eventName, handler any) *MockEventBusSubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEventBus)(nil).Subscribe), ctx, eventName, handler)
	return &MockEventBusSubscribeCall{Call: call}
}

// MockEventBusSubscribeCall wrap *gomock.Call
type MockEventBusSubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventBusSubscribeCall) Return(arg0 error) *MockEventBusSubscribeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventBusSubscribeCall) Do(f func(context.Context, string, func(context.Context, events.Event) error) error) *MockEventBusSubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventBusSubscribeCall) DoAndReturn(f func(context.Context, string, func(context.Context, events.Event) error) error) *MockEventBusSubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Unsubscribe mocks base method.
func (m *MockEventBus) Unsubscribe(ctx context.Context, eventName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, eventName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockEventBusMockRecorder) Unsubscribe(ctx, eventName any) *MockEventBusUnsubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockEventBus)(nil).Unsubscribe), ctx, eventName)
	return &MockEventBusUnsubscribeCall{Call: call}
}

// MockEventBusUnsubscribeCall wrap *gomock.Call
type MockEventBusUnsubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventBusUnsubscribeCall) Return(arg0 error) *MockEventBusUnsubscribeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventBusUnsubscribeCall) Do(f func(context.Context, string) error) *MockEventBusUnsubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventBusUnsubscribeCall) DoAndReturn(f func(context.Context, string) error) *MockEventBusUnsubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
