// Code generated by MockGen. DO NOT EDIT.
// Source: v1_api.go
//
// Generated by this command:
//
//	mockgen -typed -source=v1_api.go -destination=../../../../test/mocks/form/mock_repository.go -package=form -mock_names=V1Repository=MockRepository,WebhookRepository=MockWebhookRepository,RequestLogger=MockRequestLogger
//

// Package form is a generated GoMock package.
package form

import (
	context "context"
	reflect "reflect"
	time "time"

	auth "github.com/goformx/goforms/internal/domain/auth"
	model "github.com/goformx/goforms/internal/domain/form/model"
	submission "github.com/goformx/goforms/internal/domain/submission"
	webhook "github.com/goformx/goforms/internal/domain/webhook"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of V1Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateForm mocks base method.
func (m *MockRepository) CreateForm(arg0 context.Context, arg1 *model.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForm indicates an expected call of CreateForm.
func (mr *MockRepositoryMockRecorder) CreateForm(arg0, arg1 any) *MockRepositoryCreateFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForm", reflect.TypeOf((*MockRepository)(nil).CreateForm), arg0, arg1)
	return &MockRepositoryCreateFormCall{Call: call}
}

// MockRepositoryCreateFormCall wrap *gomock.Call
type MockRepositoryCreateFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateFormCall) Return(arg0 error) *MockRepositoryCreateFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateFormCall) Do(f func(context.Context, *model.Form) error) *MockRepositoryCreateFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateFormCall) DoAndReturn(f func(context.Context, *model.Form) error) *MockRepositoryCreateFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSchemaVersion mocks base method.
func (m *MockRepository) CreateSchemaVersion(arg0 context.Context, arg1, arg2 string, arg3 model.JSON) (*model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchemaVersion", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*model.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchemaVersion indicates an expected call of CreateSchemaVersion.
func (mr *MockRepositoryMockRecorder) CreateSchemaVersion(arg0, arg1, arg2, arg3 any) *MockRepositoryCreateSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchemaVersion", reflect.TypeOf((*MockRepository)(nil).CreateSchemaVersion), arg0, arg1, arg2, arg3)
	return &MockRepositoryCreateSchemaVersionCall{Call: call}
}

// MockRepositoryCreateSchemaVersionCall wrap *gomock.Call
type MockRepositoryCreateSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSchemaVersionCall) Return(arg0 *model.SchemaVersion, arg1 error) *MockRepositoryCreateSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSchemaVersionCall) Do(f func(context.Context, string, string, model.JSON) (*model.SchemaVersion, error)) *MockRepositoryCreateSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSchemaVersionCall) DoAndReturn(f func(context.Context, string, string, model.JSON) (*model.SchemaVersion, error)) *MockRepositoryCreateSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSubmissionIdempotent mocks base method.
func (m *MockRepository) CreateSubmissionIdempotent(arg0 context.Context, arg1 *model.FormSubmission) (*model.FormSubmission, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmissionIdempotent", arg0, arg1)
	ret0, _ := ret[0].(*model.FormSubmission)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSubmissionIdempotent indicates an expected call of CreateSubmissionIdempotent.
func (mr *MockRepositoryMockRecorder) CreateSubmissionIdempotent(arg0, arg1 any) *MockRepositoryCreateSubmissionIdempotentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmissionIdempotent", reflect.TypeOf((*MockRepository)(nil).CreateSubmissionIdempotent), arg0, arg1)
	return &MockRepositoryCreateSubmissionIdempotentCall{Call: call}
}

// MockRepositoryCreateSubmissionIdempotentCall wrap *gomock.Call
type MockRepositoryCreateSubmissionIdempotentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSubmissionIdempotentCall) Return(arg0 *model.FormSubmission, arg1 bool, arg2 error) *MockRepositoryCreateSubmissionIdempotentCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSubmissionIdempotentCall) Do(f func(context.Context, *model.FormSubmission) (*model.FormSubmission, bool, error)) *MockRepositoryCreateSubmissionIdempotentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSubmissionIdempotentCall) DoAndReturn(f func(context.Context, *model.FormSubmission) (*model.FormSubmission, bool, error)) *MockRepositoryCreateSubmissionIdempotentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFormByID mocks base method.
func (m *MockRepository) GetFormByID(arg0 context.Context, arg1, arg2 string) (*model.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormByID indicates an expected call of GetFormByID.
func (mr *MockRepositoryMockRecorder) GetFormByID(arg0, arg1, arg2 any) *MockRepositoryGetFormByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormByID", reflect.TypeOf((*MockRepository)(nil).GetFormByID), arg0, arg1, arg2)
	return &MockRepositoryGetFormByIDCall{Call: call}
}

// MockRepositoryGetFormByIDCall wrap *gomock.Call
type MockRepositoryGetFormByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetFormByIDCall) Return(arg0 *model.Form, arg1 error) *MockRepositoryGetFormByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetFormByIDCall) Do(f func(context.Context, string, string) (*model.Form, error)) *MockRepositoryGetFormByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetFormByIDCall) DoAndReturn(f func(context.Context, string, string) (*model.Form, error)) *MockRepositoryGetFormByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPublishedSchemaVersion mocks base method.
func (m *MockRepository) GetPublishedSchemaVersion(arg0 context.Context, arg1 string, arg2 int) (*model.Form, *model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedSchemaVersion", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Form)
	ret1, _ := ret[1].(*model.SchemaVersion)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPublishedSchemaVersion indicates an expected call of GetPublishedSchemaVersion.
func (mr *MockRepositoryMockRecorder) GetPublishedSchemaVersion(arg0, arg1, arg2 any) *MockRepositoryGetPublishedSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedSchemaVersion", reflect.TypeOf((*MockRepository)(nil).GetPublishedSchemaVersion), arg0, arg1, arg2)
	return &MockRepositoryGetPublishedSchemaVersionCall{Call: call}
}

// MockRepositoryGetPublishedSchemaVersionCall wrap *gomock.Call
type MockRepositoryGetPublishedSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetPublishedSchemaVersionCall) Return(arg0 *model.Form, arg1 *model.SchemaVersion, arg2 error) *MockRepositoryGetPublishedSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetPublishedSchemaVersionCall) Do(f func(context.Context, string, int) (*model.Form, *model.SchemaVersion, error)) *MockRepositoryGetPublishedSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetPublishedSchemaVersionCall) DoAndReturn(f func(context.Context, string, int) (*model.Form, *model.SchemaVersion, error)) *MockRepositoryGetPublishedSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSchemaVersion mocks base method.
func (m *MockRepository) GetSchemaVersion(arg0 context.Context, arg1, arg2 string, arg3 int) (*model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemaVersion", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*model.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchemaVersion indicates an expected call of GetSchemaVersion.
func (mr *MockRepositoryMockRecorder) GetSchemaVersion(arg0, arg1, arg2, arg3 any) *MockRepositoryGetSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemaVersion", reflect.TypeOf((*MockRepository)(nil).GetSchemaVersion), arg0, arg1, arg2, arg3)
	return &MockRepositoryGetSchemaVersionCall{Call: call}
}

// MockRepositoryGetSchemaVersionCall wrap *gomock.Call
type MockRepositoryGetSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSchemaVersionCall) Return(arg0 *model.SchemaVersion, arg1 error) *MockRepositoryGetSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSchemaVersionCall) Do(f func(context.Context, string, string, int) (*model.SchemaVersion, error)) *MockRepositoryGetSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSchemaVersionCall) DoAndReturn(f func(context.Context, string, string, int) (*model.SchemaVersion, error)) *MockRepositoryGetSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSubmissionByOrganization mocks base method.
func (m *MockRepository) GetSubmissionByOrganization(arg0 context.Context, arg1, arg2, arg3 string) (*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionByOrganization", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionByOrganization indicates an expected call of GetSubmissionByOrganization.
func (mr *MockRepositoryMockRecorder) GetSubmissionByOrganization(arg0, arg1, arg2, arg3 any) *MockRepositoryGetSubmissionByOrganizationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionByOrganization", reflect.TypeOf((*MockRepository)(nil).GetSubmissionByOrganization), arg0, arg1, arg2, arg3)
	return &MockRepositoryGetSubmissionByOrganizationCall{Call: call}
}

// MockRepositoryGetSubmissionByOrganizationCall wrap *gomock.Call
type MockRepositoryGetSubmissionByOrganizationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSubmissionByOrganizationCall) Return(arg0 *model.FormSubmission, arg1 error) *MockRepositoryGetSubmissionByOrganizationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSubmissionByOrganizationCall) Do(f func(context.Context, string, string, string) (*model.FormSubmission, error)) *MockRepositoryGetSubmissionByOrganizationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSubmissionByOrganizationCall) DoAndReturn(f func(context.Context, string, string, string) (*model.FormSubmission, error)) *MockRepositoryGetSubmissionByOrganizationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListForms mocks base method.
func (m *MockRepository) ListForms(arg0 context.Context, arg1 string, arg2 model.FormListOptions) ([]*model.Form, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForms", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.Form)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListForms indicates an expected call of ListForms.
func (mr *MockRepositoryMockRecorder) ListForms(arg0, arg1, arg2 any) *MockRepositoryListFormsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForms", reflect.TypeOf((*MockRepository)(nil).ListForms), arg0, arg1, arg2)
	return &MockRepositoryListFormsCall{Call: call}
}

// MockRepositoryListFormsCall wrap *gomock.Call
type MockRepositoryListFormsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListFormsCall) Return(arg0 []*model.Form, arg1 int64, arg2 error) *MockRepositoryListFormsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListFormsCall) Do(f func(context.Context, string, model.FormListOptions) ([]*model.Form, int64, error)) *MockRepositoryListFormsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListFormsCall) DoAndReturn(f func(context.Context, string, model.FormListOptions) ([]*model.Form, int64, error)) *MockRepositoryListFormsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSchemaVersions mocks base method.
func (m *MockRepository) ListSchemaVersions(arg0 context.Context, arg1, arg2 string, arg3, arg4 int) ([]*model.SchemaVersion, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchemaVersions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*model.SchemaVersion)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSchemaVersions indicates an expected call of ListSchemaVersions.
func (mr *MockRepositoryMockRecorder) ListSchemaVersions(arg0, arg1, arg2, arg3, arg4 any) *MockRepositoryListSchemaVersionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchemaVersions", reflect.TypeOf((*MockRepository)(nil).ListSchemaVersions), arg0, arg1, arg2, arg3, arg4)
	return &MockRepositoryListSchemaVersionsCall{Call: call}
}

// MockRepositoryListSchemaVersionsCall wrap *gomock.Call
type MockRepositoryListSchemaVersionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListSchemaVersionsCall) Return(arg0 []*model.SchemaVersion, arg1 int64, arg2 error) *MockRepositoryListSchemaVersionsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListSchemaVersionsCall) Do(f func(context.Context, string, string, int, int) ([]*model.SchemaVersion, int64, error)) *MockRepositoryListSchemaVersionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListSchemaVersionsCall) DoAndReturn(f func(context.Context, string, string, int, int) ([]*model.SchemaVersion, int64, error)) *MockRepositoryListSchemaVersionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSubmissionsPage mocks base method.
func (m *MockRepository) ListSubmissionsPage(arg0 context.Context, arg1, arg2 string, arg3 submission.ListOptions) ([]*model.FormSubmission, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubmissionsPage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.FormSubmission)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSubmissionsPage indicates an expected call of ListSubmissionsPage.
func (mr *MockRepositoryMockRecorder) ListSubmissionsPage(arg0, arg1, arg2, arg3 any) *MockRepositoryListSubmissionsPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubmissionsPage", reflect.TypeOf((*MockRepository)(nil).ListSubmissionsPage), arg0, arg1, arg2, arg3)
	return &MockRepositoryListSubmissionsPageCall{Call: call}
}

// MockRepositoryListSubmissionsPageCall wrap *gomock.Call
type MockRepositoryListSubmissionsPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListSubmissionsPageCall) Return(arg0 []*model.FormSubmission, arg1 bool, arg2 error) *MockRepositoryListSubmissionsPageCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListSubmissionsPageCall) Do(f func(context.Context, string, string, submission.ListOptions) ([]*model.FormSubmission, bool, error)) *MockRepositoryListSubmissionsPageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListSubmissionsPageCall) DoAndReturn(f func(context.Context, string, string, submission.ListOptions) ([]*model.FormSubmission, bool, error)) *MockRepositoryListSubmissionsPageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishSchemaVersion mocks base method.
func (m *MockRepository) PublishSchemaVersion(arg0 context.Context, arg1, arg2 string, arg3 int) (*model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSchemaVersion", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*model.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishSchemaVersion indicates an expected call of PublishSchemaVersion.
func (mr *MockRepositoryMockRecorder) PublishSchemaVersion(arg0, arg1, arg2, arg3 any) *MockRepositoryPublishSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSchemaVersion", reflect.TypeOf((*MockRepository)(nil).PublishSchemaVersion), arg0, arg1, arg2, arg3)
	return &MockRepositoryPublishSchemaVersionCall{Call: call}
}

// MockRepositoryPublishSchemaVersionCall wrap *gomock.Call
type MockRepositoryPublishSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryPublishSchemaVersionCall) Return(arg0 *model.SchemaVersion, arg1 error) *MockRepositoryPublishSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryPublishSchemaVersionCall) Do(f func(context.Context, string, string, int) (*model.SchemaVersion, error)) *MockRepositoryPublishSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryPublishSchemaVersionCall) DoAndReturn(f func(context.Context, string, string, int) (*model.SchemaVersion, error)) *MockRepositoryPublishSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadSubmissionExport mocks base method.
func (m *MockRepository) ReadSubmissionExport(arg0 context.Context, arg1, arg2 string, arg3 submission.ExportFilters) ([]submission.ExportRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSubmissionExport", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]submission.ExportRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSubmissionExport indicates an expected call of ReadSubmissionExport.
func (mr *MockRepositoryMockRecorder) ReadSubmissionExport(arg0, arg1, arg2, arg3 any) *MockRepositoryReadSubmissionExportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSubmissionExport", reflect.TypeOf((*MockRepository)(nil).ReadSubmissionExport), arg0, arg1, arg2, arg3)
	return &MockRepositoryReadSubmissionExportCall{Call: call}
}

// MockRepositoryReadSubmissionExportCall wrap *gomock.Call
type MockRepositoryReadSubmissionExportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryReadSubmissionExportCall) Return(arg0 []submission.ExportRecord, arg1 error) *MockRepositoryReadSubmissionExportCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryReadSubmissionExportCall) Do(f func(context.Context, string, string, submission.ExportFilters) ([]submission.ExportRecord, error)) *MockRepositoryReadSubmissionExportCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryReadSubmissionExportCall) DoAndReturn(f func(context.Context, string, string, submission.ExportFilters) ([]submission.ExportRecord, error)) *MockRepositoryReadSubmissionExportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveSubmissionExportAudit mocks base method.
func (m *MockRepository) SaveSubmissionExportAudit(arg0 context.Context, arg1 submission.ExportAudit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSubmissionExportAudit", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSubmissionExportAudit indicates an expected call of SaveSubmissionExportAudit.
func (mr *MockRepositoryMockRecorder) SaveSubmissionExportAudit(arg0, arg1 any) *MockRepositorySaveSubmissionExportAuditCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSubmissionExportAudit", reflect.TypeOf((*MockRepository)(nil).SaveSubmissionExportAudit), arg0, arg1)
	return &MockRepositorySaveSubmissionExportAuditCall{Call: call}
}

// MockRepositorySaveSubmissionExportAuditCall wrap *gomock.Call
type MockRepositorySaveSubmissionExportAuditCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySaveSubmissionExportAuditCall) Return(arg0 error) *MockRepositorySaveSubmissionExportAuditCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySaveSubmissionExportAuditCall) Do(f func(context.Context, submission.ExportAudit) error) *MockRepositorySaveSubmissionExportAuditCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySaveSubmissionExportAuditCall) DoAndReturn(f func(context.Context, submission.ExportAudit) error) *MockRepositorySaveSubmissionExportAuditCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateForm mocks base method.
func (m *MockRepository) UpdateForm(arg0 context.Context, arg1 *model.Form, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateForm", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateForm indicates an expected call of UpdateForm.
func (mr *MockRepositoryMockRecorder) UpdateForm(arg0, arg1, arg2 any) *MockRepositoryUpdateFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateForm", reflect.TypeOf((*MockRepository)(nil).UpdateForm), arg0, arg1, arg2)
	return &MockRepositoryUpdateFormCall{Call: call}
}

// MockRepositoryUpdateFormCall wrap *gomock.Call
type MockRepositoryUpdateFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateFormCall) Return(arg0 error) *MockRepositoryUpdateFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateFormCall) Do(f func(context.Context, *model.Form, time.Time) error) *MockRepositoryUpdateFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateFormCall) DoAndReturn(f func(context.Context, *model.Form, time.Time) error) *MockRepositoryUpdateFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWebhookRepository is a mock of WebhookRepository interface.
type MockWebhookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookRepositoryMockRecorder
	isgomock struct{}
}

// MockWebhookRepositoryMockRecorder is the mock recorder for MockWebhookRepository.
type MockWebhookRepositoryMockRecorder struct {
	mock *MockWebhookRepository
}

// NewMockWebhookRepository creates a new mock instance.
func NewMockWebhookRepository(ctrl *gomock.Controller) *MockWebhookRepository {
	mock := &MockWebhookRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookRepository) EXPECT() *MockWebhookRepositoryMockRecorder {
	return m.recorder
}

// DeleteWebhookEndpoint mocks base method.
func (m *MockWebhookRepository) DeleteWebhookEndpoint(arg0 context.Context, arg1, arg2 string, arg3 auth.AuditActor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhookEndpoint", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebhookEndpoint indicates an expected call of DeleteWebhookEndpoint.
func (mr *MockWebhookRepositoryMockRecorder) DeleteWebhookEndpoint(arg0, arg1, arg2, arg3 any) *MockWebhookRepositoryDeleteWebhookEndpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhookEndpoint", reflect.TypeOf((*MockWebhookRepository)(nil).DeleteWebhookEndpoint), arg0, arg1, arg2, arg3)
	return &MockWebhookRepositoryDeleteWebhookEndpointCall{Call: call}
}

// MockWebhookRepositoryDeleteWebhookEndpointCall wrap *gomock.Call
type MockWebhookRepositoryDeleteWebhookEndpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWebhookRepositoryDeleteWebhookEndpointCall) Return(arg0 error) *MockWebhookRepositoryDeleteWebhookEndpointCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWebhookRepositoryDeleteWebhookEndpointCall) Do(f func(context.Context, string, string, auth.AuditActor) error) *MockWebhookRepositoryDeleteWebhookEndpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWebhookRepositoryDeleteWebhookEndpointCall) DoAndReturn(f func(context.Context, string, string, auth.AuditActor) error) *MockWebhookRepositoryDeleteWebhookEndpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetWebhookEndpoint mocks base method.
func (m *MockWebhookRepository) GetWebhookEndpoint(arg0 context.Context, arg1, arg2 string) (*webhook.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookEndpoint", arg0, arg1, arg2)
	ret0, _ := ret[0].(*webhook.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookEndpoint indicates an expected call of GetWebhookEndpoint.
func (mr *MockWebhookRepositoryMockRecorder) GetWebhookEndpoint(arg0, arg1, arg2 any) *MockWebhookRepositoryGetWebhookEndpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookEndpoint", reflect.TypeOf((*MockWebhookRepository)(nil).GetWebhookEndpoint), arg0, arg1, arg2)
	return &MockWebhookRepositoryGetWebhookEndpointCall{Call: call}
}

// MockWebhookRepositoryGetWebhookEndpointCall wrap *gomock.Call
type MockWebhookRepositoryGetWebhookEndpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWebhookRepositoryGetWebhookEndpointCall) Return(arg0 *webhook.Endpoint, arg1 error) *MockWebhookRepositoryGetWebhookEndpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWebhookRepositoryGetWebhookEndpointCall) Do(f func(context.Context, string, string) (*webhook.Endpoint, error)) *MockWebhookRepositoryGetWebhookEndpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWebhookRepositoryGetWebhookEndpointCall) DoAndReturn(f func(context.Context, string, string) (*webhook.Endpoint, error)) *MockWebhookRepositoryGetWebhookEndpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListWebhookDeliveries mocks base method.
func (m *MockWebhookRepository) ListWebhookDeliveries(arg0 context.Context, arg1, arg2 string, arg3 int) ([]*webhook.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhookDeliveries", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*webhook.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebhookDeliveries indicates an expected call of ListWebhookDeliveries.
func (mr *MockWebhookRepositoryMockRecorder) ListWebhookDeliveries(arg0, arg1, arg2, arg3 any) *MockWebhookRepositoryListWebhookDeliveriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhookDeliveries", reflect.TypeOf((*MockWebhookRepository)(nil).ListWebhookDeliveries), arg0, arg1, arg2, arg3)
	return &MockWebhookRepositoryListWebhookDeliveriesCall{Call: call}
}

// MockWebhookRepositoryListWebhookDeliveriesCall wrap *gomock.Call
type MockWebhookRepositoryListWebhookDeliveriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWebhookRepositoryListWebhookDeliveriesCall) Return(arg0 []*webhook.Delivery, arg1 error) *MockWebhookRepositoryListWebhookDeliveriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWebhookRepositoryListWebhookDeliveriesCall) Do(f func(context.Context, string, string, int) ([]*webhook.Delivery, error)) *MockWebhookRepositoryListWebhookDeliveriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWebhookRepositoryListWebhookDeliveriesCall) DoAndReturn(f func(context.Context, string, string, int) ([]*webhook.Delivery, error)) *MockWebhookRepositoryListWebhookDeliveriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PatchWebhookEndpoint mocks base method.
func (m *MockWebhookRepository) PatchWebhookEndpoint(arg0 context.Context, arg1, arg2 string, arg3 webhook.EndpointChange, arg4 auth.AuditActor) (*webhook.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchWebhookEndpoint", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*webhook.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchWebhookEndpoint indicates an expected call of PatchWebhookEndpoint.
func (mr *MockWebhookRepositoryMockRecorder) PatchWebhookEndpoint(arg0, arg1, arg2, arg3, arg4 any) *MockWebhookRepositoryPatchWebhookEndpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchWebhookEndpoint", reflect.TypeOf((*MockWebhookRepository)(nil).PatchWebhookEndpoint), arg0, arg1, arg2, arg3, arg4)
	return &MockWebhookRepositoryPatchWebhookEndpointCall{Call: call}
}

// MockWebhookRepositoryPatchWebhookEndpointCall wrap *gomock.Call
type MockWebhookRepositoryPatchWebhookEndpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWebhookRepositoryPatchWebhookEndpointCall) Return(arg0 *webhook.Endpoint, arg1 error) *MockWebhookRepositoryPatchWebhookEndpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWebhookRepositoryPatchWebhookEndpointCall) Do(f func(context.Context, string, string, webhook.EndpointChange, auth.AuditActor) (*webhook.Endpoint, error)) *MockWebhookRepositoryPatchWebhookEndpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWebhookRepositoryPatchWebhookEndpointCall) DoAndReturn(f func(context.Context, string, string, webhook.EndpointChange, auth.AuditActor) (*webhook.Endpoint, error)) *MockWebhookRepositoryPatchWebhookEndpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutWebhookEndpoint mocks base method.
func (m *MockWebhookRepository) PutWebhookEndpoint(arg0 context.Context, arg1, arg2, arg3 string, arg4 webhook.SecretConfig, arg5 bool, arg6 auth.AuditActor) (*webhook.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutWebhookEndpoint", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*webhook.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutWebhookEndpoint indicates an expected call of PutWebhookEndpoint.
func (mr *MockWebhookRepositoryMockRecorder) PutWebhookEndpoint(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *MockWebhookRepositoryPutWebhookEndpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutWebhookEndpoint", reflect.TypeOf((*MockWebhookRepository)(nil).PutWebhookEndpoint), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	return &MockWebhookRepositoryPutWebhookEndpointCall{Call: call}
}

// MockWebhookRepositoryPutWebhookEndpointCall wrap *gomock.Call
type MockWebhookRepositoryPutWebhookEndpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWebhookRepositoryPutWebhookEndpointCall) Return(arg0 *webhook.Endpoint, arg1 error) *MockWebhookRepositoryPutWebhookEndpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWebhookRepositoryPutWebhookEndpointCall) Do(f func(context.Context, string, string, string, webhook.SecretConfig, bool, auth.AuditActor) (*webhook.Endpoint, error)) *MockWebhookRepositoryPutWebhookEndpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWebhookRepositoryPutWebhookEndpointCall) DoAndReturn(f func(context.Context, string, string, string, webhook.SecretConfig, bool, auth.AuditActor) (*webhook.Endpoint, error)) *MockWebhookRepositoryPutWebhookEndpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplayWebhookDelivery mocks base method.
func (m *MockWebhookRepository) ReplayWebhookDelivery(arg0 context.Context, arg1, arg2, arg3 string, arg4 auth.AuditActor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayWebhookDelivery", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplayWebhookDelivery indicates an expected call of ReplayWebhookDelivery.
func (mr *MockWebhookRepositoryMockRecorder) ReplayWebhookDelivery(arg0, arg1, arg2, arg3, arg4 any) *MockWebhookRepositoryReplayWebhookDeliveryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayWebhookDelivery", reflect.TypeOf((*MockWebhookRepository)(nil).ReplayWebhookDelivery), arg0, arg1, arg2, arg3, arg4)
	return &MockWebhookRepositoryReplayWebhookDeliveryCall{Call: call}
}

// MockWebhookRepositoryReplayWebhookDeliveryCall wrap *gomock.Call
type MockWebhookRepositoryReplayWebhookDeliveryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWebhookRepositoryReplayWebhookDeliveryCall) Return(arg0 error) *MockWebhookRepositoryReplayWebhookDeliveryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWebhookRepositoryReplayWebhookDeliveryCall) Do(f func(context.Context, string, string, string, auth.AuditActor) error) *MockWebhookRepositoryReplayWebhookDeliveryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWebhookRepositoryReplayWebhookDeliveryCall) DoAndReturn(f func(context.Context, string, string, string, auth.AuditActor) error) *MockWebhookRepositoryReplayWebhookDeliveryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockServiceTokenManagementRepository is a mock of ServiceTokenManagementRepository interface.
type MockServiceTokenManagementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceTokenManagementRepositoryMockRecorder
	isgomock struct{}
}

// MockServiceTokenManagementRepositoryMockRecorder is the mock recorder for MockServiceTokenManagementRepository.
type MockServiceTokenManagementRepositoryMockRecorder struct {
	mock *MockServiceTokenManagementRepository
}

// NewMockServiceTokenManagementRepository creates a new mock instance.
func NewMockServiceTokenManagementRepository(ctrl *gomock.Controller) *MockServiceTokenManagementRepository {
	mock := &MockServiceTokenManagementRepository{ctrl: ctrl}
	mock.recorder = &MockServiceTokenManagementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceTokenManagementRepository) EXPECT() *MockServiceTokenManagementRepositoryMockRecorder {
	return m.recorder
}

// ListByOrganization mocks base method.
func (m *MockServiceTokenManagementRepository) ListByOrganization(arg0 context.Context, arg1 string, arg2 int) ([]*auth.ServiceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganization", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*auth.ServiceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOrganization indicates an expected call of ListByOrganization.
func (mr *MockServiceTokenManagementRepositoryMockRecorder) ListByOrganization(arg0, arg1, arg2 any) *MockServiceTokenManagementRepositoryListByOrganizationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganization", reflect.TypeOf((*MockServiceTokenManagementRepository)(nil).ListByOrganization), arg0, arg1, arg2)
	return &MockServiceTokenManagementRepositoryListByOrganizationCall{Call: call}
}

// MockServiceTokenManagementRepositoryListByOrganizationCall wrap *gomock.Call
type MockServiceTokenManagementRepositoryListByOrganizationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTokenManagementRepositoryListByOrganizationCall) Return(arg0 []*auth.ServiceToken, arg1 error) *MockServiceTokenManagementRepositoryListByOrganizationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTokenManagementRepositoryListByOrganizationCall) Do(f func(context.Context, string, int) ([]*auth.ServiceToken, error)) *MockServiceTokenManagementRepositoryListByOrganizationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTokenManagementRepositoryListByOrganizationCall) DoAndReturn(f func(context.Context, string, int) ([]*auth.ServiceToken, error)) *MockServiceTokenManagementRepositoryListByOrganizationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeByOrganization mocks base method.
func (m *MockServiceTokenManagementRepository) RevokeByOrganization(arg0 context.Context, arg1, arg2 string, arg3 time.Time, arg4 auth.AuditActor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByOrganization", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByOrganization indicates an expected call of RevokeByOrganization.
func (mr *MockServiceTokenManagementRepositoryMockRecorder) RevokeByOrganization(arg0, arg1, arg2, arg3, arg4 any) *MockServiceTokenManagementRepositoryRevokeByOrganizationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByOrganization", reflect.TypeOf((*MockServiceTokenManagementRepository)(nil).RevokeByOrganization), arg0, arg1, arg2, arg3, arg4)
	return &MockServiceTokenManagementRepositoryRevokeByOrganizationCall{Call: call}
}

// MockServiceTokenManagementRepositoryRevokeByOrganizationCall wrap *gomock.Call
type MockServiceTokenManagementRepositoryRevokeByOrganizationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTokenManagementRepositoryRevokeByOrganizationCall) Return(arg0 error) *MockServiceTokenManagementRepositoryRevokeByOrganizationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTokenManagementRepositoryRevokeByOrganizationCall) Do(f func(context.Context, string, string, time.Time, auth.AuditActor) error) *MockServiceTokenManagementRepositoryRevokeByOrganizationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTokenManagementRepositoryRevokeByOrganizationCall) DoAndReturn(f func(context.Context, string, string, time.Time, auth.AuditActor) error) *MockServiceTokenManagementRepositoryRevokeByOrganizationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockServiceTokenManagementRepository) Save(arg0 context.Context, arg1 *auth.ServiceToken, arg2 auth.AuditActor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServiceTokenManagementRepositoryMockRecorder) Save(arg0, arg1, arg2 any) *MockServiceTokenManagementRepositorySaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockServiceTokenManagementRepository)(nil).Save), arg0, arg1, arg2)
	return &MockServiceTokenManagementRepositorySaveCall{Call: call}
}

// MockServiceTokenManagementRepositorySaveCall wrap *gomock.Call
type MockServiceTokenManagementRepositorySaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTokenManagementRepositorySaveCall) Return(arg0 error) *MockServiceTokenManagementRepositorySaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTokenManagementRepositorySaveCall) Do(f func(context.Context, *auth.ServiceToken, auth.AuditActor) error) *MockServiceTokenManagementRepositorySaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTokenManagementRepositorySaveCall) DoAndReturn(f func(context.Context, *auth.ServiceToken, auth.AuditActor) error) *MockServiceTokenManagementRepositorySaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRequestLogger is a mock of RequestLogger interface.
type MockRequestLogger struct {
	ctrl     *gomock.Controller
	recorder *MockRequestLoggerMockRecorder
	isgomock struct{}
}

// MockRequestLoggerMockRecorder is the mock recorder for MockRequestLogger.
type MockRequestLoggerMockRecorder struct {
	mock *MockRequestLogger
}

// NewMockRequestLogger creates a new mock instance.
func NewMockRequestLogger(ctrl *gomock.Controller) *MockRequestLogger {
	mock := &MockRequestLogger{ctrl: ctrl}
	mock.recorder = &MockRequestLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestLogger) EXPECT() *MockRequestLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockRequestLogger) Error(arg0 string, arg1 ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockRequestLoggerMockRecorder) Error(arg0 any, arg1 ...any) *MockRequestLoggerErrorCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockRequestLogger)(nil).Error), varargs...)
	return &MockRequestLoggerErrorCall{Call: call}
}

// MockRequestLoggerErrorCall wrap *gomock.Call
type MockRequestLoggerErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRequestLoggerErrorCall) Return() *MockRequestLoggerErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRequestLoggerErrorCall) Do(f func(string, ...any)) *MockRequestLoggerErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRequestLoggerErrorCall) DoAndReturn(f func(string, ...any)) *MockRequestLoggerErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Info mocks base method.
func (m *MockRequestLogger) Info(arg0 string, arg1 ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockRequestLoggerMockRecorder) Info(arg0 any, arg1 ...any) *MockRequestLoggerInfoCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockRequestLogger)(nil).Info), varargs...)
	return &MockRequestLoggerInfoCall{Call: call}
}

// MockRequestLoggerInfoCall wrap *gomock.Call
type MockRequestLoggerInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRequestLoggerInfoCall) Return() *MockRequestLoggerInfoCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRequestLoggerInfoCall) Do(f func(string, ...any)) *MockRequestLoggerInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRequestLoggerInfoCall) DoAndReturn(f func(string, ...any)) *MockRequestLoggerInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
