// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -typed -source=service.go -destination=../../../test/mocks/form/mock_service.go -package=form -mock_names=Service=MockService
//

// Package form is a generated GoMock package.
package form

import (
	context "context"
	reflect "reflect"

	model "github.com/goformx/goforms/internal/domain/form/model"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CountFormsByUser mocks base method.
func (m *MockService) CountFormsByUser(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFormsByUser", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFormsByUser indicates an expected call of CountFormsByUser.
func (mr *MockServiceMockRecorder) CountFormsByUser(ctx, userID any) *MockServiceCountFormsByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFormsByUser", reflect.TypeOf((*MockService)(nil).CountFormsByUser), ctx, userID)
	return &MockServiceCountFormsByUserCall{Call: call}
}

// MockServiceCountFormsByUserCall wrap *gomock.Call
type MockServiceCountFormsByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCountFormsByUserCall) Return(arg0 int, arg1 error) *MockServiceCountFormsByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCountFormsByUserCall) Do(f func(context.Context, string) (int, error)) *MockServiceCountFormsByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCountFormsByUserCall) DoAndReturn(f func(context.Context, string) (int, error)) *MockServiceCountFormsByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountSubmissionsByUserMonth mocks base method.
func (m *MockService) CountSubmissionsByUserMonth(ctx context.Context, userID string, year, month int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubmissionsByUserMonth", ctx, userID, year, month)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubmissionsByUserMonth indicates an expected call of CountSubmissionsByUserMonth.
func (mr *MockServiceMockRecorder) CountSubmissionsByUserMonth(ctx, userID, year, month any) *MockServiceCountSubmissionsByUserMonthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubmissionsByUserMonth", reflect.TypeOf((*MockService)(nil).CountSubmissionsByUserMonth), ctx, userID, year, month)
	return &MockServiceCountSubmissionsByUserMonthCall{Call: call}
}

// MockServiceCountSubmissionsByUserMonthCall wrap *gomock.Call
type MockServiceCountSubmissionsByUserMonthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCountSubmissionsByUserMonthCall) Return(arg0 int, arg1 error) *MockServiceCountSubmissionsByUserMonthCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCountSubmissionsByUserMonthCall) Do(f func(context.Context, string, int, int) (int, error)) *MockServiceCountSubmissionsByUserMonthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCountSubmissionsByUserMonthCall) DoAndReturn(f func(context.Context, string, int, int) (int, error)) *MockServiceCountSubmissionsByUserMonthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateForm mocks base method.
func (m *MockService) CreateForm(ctx context.Context, form *model.Form, planTier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForm", ctx, form, planTier)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForm indicates an expected call of CreateForm.
func (mr *MockServiceMockRecorder) CreateForm(ctx, form, planTier any) *MockServiceCreateFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForm", reflect.TypeOf((*MockService)(nil).CreateForm), ctx, form, planTier)
	return &MockServiceCreateFormCall{Call: call}
}

// MockServiceCreateFormCall wrap *gomock.Call
type MockServiceCreateFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateFormCall) Return(arg0 error) *MockServiceCreateFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateFormCall) Do(f func(context.Context, *model.Form, string) error) *MockServiceCreateFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateFormCall) DoAndReturn(f func(context.Context, *model.Form, string) error) *MockServiceCreateFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteForm mocks base method.
func (m *MockService) DeleteForm(ctx context.Context, formID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForm", ctx, formID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForm indicates an expected call of DeleteForm.
func (mr *MockServiceMockRecorder) DeleteForm(ctx, formID any) *MockServiceDeleteFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForm", reflect.TypeOf((*MockService)(nil).DeleteForm), ctx, formID)
	return &MockServiceDeleteFormCall{Call: call}
}

// MockServiceDeleteFormCall wrap *gomock.Call
type MockServiceDeleteFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteFormCall) Return(arg0 error) *MockServiceDeleteFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteFormCall) Do(f func(context.Context, string) error) *MockServiceDeleteFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteFormCall) DoAndReturn(f func(context.Context, string) error) *MockServiceDeleteFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetForm mocks base method.
func (m *MockService) GetForm(ctx context.Context, formID string) (*model.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForm", ctx, formID)
	ret0, _ := ret[0].(*model.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForm indicates an expected call of GetForm.
func (mr *MockServiceMockRecorder) GetForm(ctx, formID any) *MockServiceGetFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForm", reflect.TypeOf((*MockService)(nil).GetForm), ctx, formID)
	return &MockServiceGetFormCall{Call: call}
}

// MockServiceGetFormCall wrap *gomock.Call
type MockServiceGetFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetFormCall) Return(arg0 *model.Form, arg1 error) *MockServiceGetFormCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetFormCall) Do(f func(context.Context, string) (*model.Form, error)) *MockServiceGetFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetFormCall) DoAndReturn(f func(context.Context, string) (*model.Form, error)) *MockServiceGetFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFormSubmission mocks base method.
func (m *MockService) GetFormSubmission(ctx context.Context, submissionID string) (*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormSubmission", ctx, submissionID)
	ret0, _ := ret[0].(*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormSubmission indicates an expected call of GetFormSubmission.
func (mr *MockServiceMockRecorder) GetFormSubmission(ctx, submissionID any) *MockServiceGetFormSubmissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormSubmission", reflect.TypeOf((*MockService)(nil).GetFormSubmission), ctx, submissionID)
	return &MockServiceGetFormSubmissionCall{Call: call}
}

// MockServiceGetFormSubmissionCall wrap *gomock.Call
type MockServiceGetFormSubmissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetFormSubmissionCall) Return(arg0 *model.FormSubmission, arg1 error) *MockServiceGetFormSubmissionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetFormSubmissionCall) Do(f func(context.Context, string) (*model.FormSubmission, error)) *MockServiceGetFormSubmissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetFormSubmissionCall) DoAndReturn(f func(context.Context, string) (*model.FormSubmission, error)) *MockServiceGetFormSubmissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListFormSubmissions mocks base method.
func (m *MockService) ListFormSubmissions(ctx context.Context, formID string) ([]*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFormSubmissions", ctx, formID)
	ret0, _ := ret[0].([]*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFormSubmissions indicates an expected call of ListFormSubmissions.
func (mr *MockServiceMockRecorder) ListFormSubmissions(ctx, formID any) *MockServiceListFormSubmissionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFormSubmissions", reflect.TypeOf((*MockService)(nil).ListFormSubmissions), ctx, formID)
	return &MockServiceListFormSubmissionsCall{Call: call}
}

// MockServiceListFormSubmissionsCall wrap *gomock.Call
type MockServiceListFormSubmissionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListFormSubmissionsCall) Return(arg0 []*model.FormSubmission, arg1 error) *MockServiceListFormSubmissionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListFormSubmissionsCall) Do(f func(context.Context, string) ([]*model.FormSubmission, error)) *MockServiceListFormSubmissionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListFormSubmissionsCall) DoAndReturn(f func(context.Context, string) ([]*model.FormSubmission, error)) *MockServiceListFormSubmissionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListForms mocks base method.
func (m *MockService) ListForms(ctx context.Context, userID string) ([]*model.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForms", ctx, userID)
	ret0, _ := ret[0].([]*model.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForms indicates an expected call of ListForms.
func (mr *MockServiceMockRecorder) ListForms(ctx, userID any) *MockServiceListFormsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForms", reflect.TypeOf((*MockService)(nil).ListForms), ctx, userID)
	return &MockServiceListFormsCall{Call: call}
}

// MockServiceListFormsCall wrap *gomock.Call
type MockServiceListFormsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListFormsCall) Return(arg0 []*model.Form, arg1 error) *MockServiceListFormsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListFormsCall) Do(f func(context.Context, string) ([]*model.Form, error)) *MockServiceListFormsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListFormsCall) DoAndReturn(f func(context.Context, string) ([]*model.Form, error)) *MockServiceListFormsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitForm mocks base method.
func (m *MockService) SubmitForm(ctx context.Context, submission *model.FormSubmission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitForm", ctx, submission)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitForm indicates an expected call of SubmitForm.
func (mr *MockServiceMockRecorder) SubmitForm(ctx, submission any) *MockServiceSubmitFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitForm", reflect.TypeOf((*MockService)(nil).SubmitForm), ctx, submission)
	return &MockServiceSubmitFormCall{Call: call}
}

// MockServiceSubmitFormCall wrap *gomock.Call
type MockServiceSubmitFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSubmitFormCall) Return(arg0 error) *MockServiceSubmitFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSubmitFormCall) Do(f func(context.Context, *model.FormSubmission) error) *MockServiceSubmitFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSubmitFormCall) DoAndReturn(f func(context.Context, *model.FormSubmission) error) *MockServiceSubmitFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TrackFormAnalytics mocks base method.
func (m *MockService) TrackFormAnalytics(ctx context.Context, formID, eventType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackFormAnalytics", ctx, formID, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackFormAnalytics indicates an expected call of TrackFormAnalytics.
func (mr *MockServiceMockRecorder) TrackFormAnalytics(ctx, formID, eventType any) *MockServiceTrackFormAnalyticsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackFormAnalytics", reflect.TypeOf((*MockService)(nil).TrackFormAnalytics), ctx, formID, eventType)
	return &MockServiceTrackFormAnalyticsCall{Call: call}
}

// MockServiceTrackFormAnalyticsCall wrap *gomock.Call
type MockServiceTrackFormAnalyticsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTrackFormAnalyticsCall) Return(arg0 error) *MockServiceTrackFormAnalyticsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTrackFormAnalyticsCall) Do(f func(context.Context, string, string) error) *MockServiceTrackFormAnalyticsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTrackFormAnalyticsCall) DoAndReturn(f func(context.Context, string, string) error) *MockServiceTrackFormAnalyticsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateForm mocks base method.
func (m *MockService) UpdateForm(ctx context.Context, form *model.Form, planTier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateForm", ctx, form, planTier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateForm indicates an expected call of UpdateForm.
func (mr *MockServiceMockRecorder) UpdateForm(ctx, form, planTier any) *MockServiceUpdateFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateForm", reflect.TypeOf((*MockService)(nil).UpdateForm), ctx, form, planTier)
	return &MockServiceUpdateFormCall{Call: call}
}

// MockServiceUpdateFormCall wrap *gomock.Call
type MockServiceUpdateFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateFormCall) Return(arg0 error) *MockServiceUpdateFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateFormCall) Do(f func(context.Context, *model.Form, string) error) *MockServiceUpdateFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateFormCall) DoAndReturn(f func(context.Context, *model.Form, string) error) *MockServiceUpdateFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateFormState mocks base method.
func (m *MockService) UpdateFormState(ctx context.Context, formID, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFormState", ctx, formID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFormState indicates an expected call of UpdateFormState.
func (mr *MockServiceMockRecorder) UpdateFormState(ctx, formID, state any) *MockServiceUpdateFormStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFormState", reflect.TypeOf((*MockService)(nil).UpdateFormState), ctx, formID, state)
	return &MockServiceUpdateFormStateCall{Call: call}
}

// MockServiceUpdateFormStateCall wrap *gomock.Call
type MockServiceUpdateFormStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateFormStateCall) Return(arg0 error) *MockServiceUpdateFormStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateFormStateCall) Do(f func(context.Context, string, string) error) *MockServiceUpdateFormStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateFormStateCall) DoAndReturn(f func(context.Context, string, string) error) *MockServiceUpdateFormStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
