// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -typed -source=repository.go -destination=../../../test/mocks/form/mock_repository.go -package=form
//

// Package form is a generated GoMock package.
package form

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/goformx/goforms/internal/domain/form/model"
	common "github.com/goformx/goforms/internal/infrastructure/repository/common"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountFormsByUser mocks base method.
func (m *MockRepository) CountFormsByUser(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFormsByUser", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFormsByUser indicates an expected call of CountFormsByUser.
func (mr *MockRepositoryMockRecorder) CountFormsByUser(ctx, userID any) *MockRepositoryCountFormsByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFormsByUser", reflect.TypeOf((*MockRepository)(nil).CountFormsByUser), ctx, userID)
	return &MockRepositoryCountFormsByUserCall{Call: call}
}

// MockRepositoryCountFormsByUserCall wrap *gomock.Call
type MockRepositoryCountFormsByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCountFormsByUserCall) Return(arg0 int, arg1 error) *MockRepositoryCountFormsByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCountFormsByUserCall) Do(f func(context.Context, string) (int, error)) *MockRepositoryCountFormsByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCountFormsByUserCall) DoAndReturn(f func(context.Context, string) (int, error)) *MockRepositoryCountFormsByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountSubmissionsByUserMonth mocks base method.
func (m *MockRepository) CountSubmissionsByUserMonth(ctx context.Context, userID string, year, month int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubmissionsByUserMonth", ctx, userID, year, month)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubmissionsByUserMonth indicates an expected call of CountSubmissionsByUserMonth.
func (mr *MockRepositoryMockRecorder) CountSubmissionsByUserMonth(ctx, userID, year, month any) *MockRepositoryCountSubmissionsByUserMonthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubmissionsByUserMonth", reflect.TypeOf((*MockRepository)(nil).CountSubmissionsByUserMonth), ctx, userID, year, month)
	return &MockRepositoryCountSubmissionsByUserMonthCall{Call: call}
}

// MockRepositoryCountSubmissionsByUserMonthCall wrap *gomock.Call
type MockRepositoryCountSubmissionsByUserMonthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCountSubmissionsByUserMonthCall) Return(arg0 int, arg1 error) *MockRepositoryCountSubmissionsByUserMonthCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCountSubmissionsByUserMonthCall) Do(f func(context.Context, string, int, int) (int, error)) *MockRepositoryCountSubmissionsByUserMonthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCountSubmissionsByUserMonthCall) DoAndReturn(f func(context.Context, string, int, int) (int, error)) *MockRepositoryCountSubmissionsByUserMonthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateForm mocks base method.
func (m *MockRepository) CreateForm(ctx context.Context, form *model.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForm", ctx, form)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForm indicates an expected call of CreateForm.
func (mr *MockRepositoryMockRecorder) CreateForm(ctx, form any) *MockRepositoryCreateFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForm", reflect.TypeOf((*MockRepository)(nil).CreateForm), ctx, form)
	return &MockRepositoryCreateFormCall{Call: call}
}

// MockRepositoryCreateFormCall wrap *gomock.Call
type MockRepositoryCreateFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateFormCall) Return(arg0 error) *MockRepositoryCreateFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateFormCall) Do(f func(context.Context, *model.Form) error) *MockRepositoryCreateFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateFormCall) DoAndReturn(f func(context.Context, *model.Form) error) *MockRepositoryCreateFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSchemaVersion mocks base method.
func (m *MockRepository) CreateSchemaVersion(ctx context.Context, formID string, schema model.JSON) (*model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchemaVersion", ctx, formID, schema)
	ret0, _ := ret[0].(*model.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchemaVersion indicates an expected call of CreateSchemaVersion.
func (mr *MockRepositoryMockRecorder) CreateSchemaVersion(ctx, formID, schema any) *MockRepositoryCreateSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchemaVersion", reflect.TypeOf((*MockRepository)(nil).CreateSchemaVersion), ctx, formID, schema)
	return &MockRepositoryCreateSchemaVersionCall{Call: call}
}

// MockRepositoryCreateSchemaVersionCall wrap *gomock.Call
type MockRepositoryCreateSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSchemaVersionCall) Return(arg0 *model.SchemaVersion, arg1 error) *MockRepositoryCreateSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSchemaVersionCall) Do(f func(context.Context, string, model.JSON) (*model.SchemaVersion, error)) *MockRepositoryCreateSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSchemaVersionCall) DoAndReturn(f func(context.Context, string, model.JSON) (*model.SchemaVersion, error)) *MockRepositoryCreateSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSubmission mocks base method.
func (m *MockRepository) CreateSubmission(ctx context.Context, submission *model.FormSubmission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmission", ctx, submission)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubmission indicates an expected call of CreateSubmission.
func (mr *MockRepositoryMockRecorder) CreateSubmission(ctx, submission any) *MockRepositoryCreateSubmissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmission", reflect.TypeOf((*MockRepository)(nil).CreateSubmission), ctx, submission)
	return &MockRepositoryCreateSubmissionCall{Call: call}
}

// MockRepositoryCreateSubmissionCall wrap *gomock.Call
type MockRepositoryCreateSubmissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSubmissionCall) Return(arg0 error) *MockRepositoryCreateSubmissionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSubmissionCall) Do(f func(context.Context, *model.FormSubmission) error) *MockRepositoryCreateSubmissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSubmissionCall) DoAndReturn(f func(context.Context, *model.FormSubmission) error) *MockRepositoryCreateSubmissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSubmissionIdempotent mocks base method.
func (m *MockRepository) CreateSubmissionIdempotent(ctx context.Context, submission *model.FormSubmission) (*model.FormSubmission, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmissionIdempotent", ctx, submission)
	ret0, _ := ret[0].(*model.FormSubmission)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSubmissionIdempotent indicates an expected call of CreateSubmissionIdempotent.
func (mr *MockRepositoryMockRecorder) CreateSubmissionIdempotent(ctx, submission any) *MockRepositoryCreateSubmissionIdempotentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmissionIdempotent", reflect.TypeOf((*MockRepository)(nil).CreateSubmissionIdempotent), ctx, submission)
	return &MockRepositoryCreateSubmissionIdempotentCall{Call: call}
}

// MockRepositoryCreateSubmissionIdempotentCall wrap *gomock.Call
type MockRepositoryCreateSubmissionIdempotentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateSubmissionIdempotentCall) Return(arg0 *model.FormSubmission, arg1 bool, arg2 error) *MockRepositoryCreateSubmissionIdempotentCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateSubmissionIdempotentCall) Do(f func(context.Context, *model.FormSubmission) (*model.FormSubmission, bool, error)) *MockRepositoryCreateSubmissionIdempotentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateSubmissionIdempotentCall) DoAndReturn(f func(context.Context, *model.FormSubmission) (*model.FormSubmission, bool, error)) *MockRepositoryCreateSubmissionIdempotentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteForm mocks base method.
func (m *MockRepository) DeleteForm(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForm", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForm indicates an expected call of DeleteForm.
func (mr *MockRepositoryMockRecorder) DeleteForm(ctx, id any) *MockRepositoryDeleteFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForm", reflect.TypeOf((*MockRepository)(nil).DeleteForm), ctx, id)
	return &MockRepositoryDeleteFormCall{Call: call}
}

// MockRepositoryDeleteFormCall wrap *gomock.Call
type MockRepositoryDeleteFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteFormCall) Return(arg0 error) *MockRepositoryDeleteFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteFormCall) Do(f func(context.Context, string) error) *MockRepositoryDeleteFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteFormCall) DoAndReturn(f func(context.Context, string) error) *MockRepositoryDeleteFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSubmission mocks base method.
func (m *MockRepository) DeleteSubmission(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubmission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubmission indicates an expected call of DeleteSubmission.
func (mr *MockRepositoryMockRecorder) DeleteSubmission(ctx, id any) *MockRepositoryDeleteSubmissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubmission", reflect.TypeOf((*MockRepository)(nil).DeleteSubmission), ctx, id)
	return &MockRepositoryDeleteSubmissionCall{Call: call}
}

// MockRepositoryDeleteSubmissionCall wrap *gomock.Call
type MockRepositoryDeleteSubmissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDeleteSubmissionCall) Return(arg0 error) *MockRepositoryDeleteSubmissionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDeleteSubmissionCall) Do(f func(context.Context, string) error) *MockRepositoryDeleteSubmissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDeleteSubmissionCall) DoAndReturn(f func(context.Context, string) error) *MockRepositoryDeleteSubmissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByFormAndUser mocks base method.
func (m *MockRepository) GetByFormAndUser(ctx context.Context, formID, userID string) (*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFormAndUser", ctx, formID, userID)
	ret0, _ := ret[0].(*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFormAndUser indicates an expected call of GetByFormAndUser.
func (mr *MockRepositoryMockRecorder) GetByFormAndUser(ctx, formID, userID any) *MockRepositoryGetByFormAndUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFormAndUser", reflect.TypeOf((*MockRepository)(nil).GetByFormAndUser), ctx, formID, userID)
	return &MockRepositoryGetByFormAndUserCall{Call: call}
}

// MockRepositoryGetByFormAndUserCall wrap *gomock.Call
type MockRepositoryGetByFormAndUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetByFormAndUserCall) Return(arg0 *model.FormSubmission, arg1 error) *MockRepositoryGetByFormAndUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetByFormAndUserCall) Do(f func(context.Context, string, string) (*model.FormSubmission, error)) *MockRepositoryGetByFormAndUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetByFormAndUserCall) DoAndReturn(f func(context.Context, string, string) (*model.FormSubmission, error)) *MockRepositoryGetByFormAndUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByFormID mocks base method.
func (m *MockRepository) GetByFormID(ctx context.Context, formID string) ([]*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFormID", ctx, formID)
	ret0, _ := ret[0].([]*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFormID indicates an expected call of GetByFormID.
func (mr *MockRepositoryMockRecorder) GetByFormID(ctx, formID any) *MockRepositoryGetByFormIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFormID", reflect.TypeOf((*MockRepository)(nil).GetByFormID), ctx, formID)
	return &MockRepositoryGetByFormIDCall{Call: call}
}

// MockRepositoryGetByFormIDCall wrap *gomock.Call
type MockRepositoryGetByFormIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetByFormIDCall) Return(arg0 []*model.FormSubmission, arg1 error) *MockRepositoryGetByFormIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetByFormIDCall) Do(f func(context.Context, string) ([]*model.FormSubmission, error)) *MockRepositoryGetByFormIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetByFormIDCall) DoAndReturn(f func(context.Context, string) ([]*model.FormSubmission, error)) *MockRepositoryGetByFormIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByFormIDPaginated mocks base method.
func (m *MockRepository) GetByFormIDPaginated(ctx context.Context, formID string, params common.PaginationParams) (*common.PaginationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFormIDPaginated", ctx, formID, params)
	ret0, _ := ret[0].(*common.PaginationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFormIDPaginated indicates an expected call of GetByFormIDPaginated.
func (mr *MockRepositoryMockRecorder) GetByFormIDPaginated(ctx, formID, params any) *MockRepositoryGetByFormIDPaginatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFormIDPaginated", reflect.TypeOf((*MockRepository)(nil).GetByFormIDPaginated), ctx, formID, params)
	return &MockRepositoryGetByFormIDPaginatedCall{Call: call}
}

// MockRepositoryGetByFormIDPaginatedCall wrap *gomock.Call
type MockRepositoryGetByFormIDPaginatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetByFormIDPaginatedCall) Return(arg0 *common.PaginationResult, arg1 error) *MockRepositoryGetByFormIDPaginatedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetByFormIDPaginatedCall) Do(f func(context.Context, string, common.PaginationParams) (*common.PaginationResult, error)) *MockRepositoryGetByFormIDPaginatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetByFormIDPaginatedCall) DoAndReturn(f func(context.Context, string, common.PaginationParams) (*common.PaginationResult, error)) *MockRepositoryGetByFormIDPaginatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFormByID mocks base method.
func (m *MockRepository) GetFormByID(ctx context.Context, id string) (*model.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormByID", ctx, id)
	ret0, _ := ret[0].(*model.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormByID indicates an expected call of GetFormByID.
func (mr *MockRepositoryMockRecorder) GetFormByID(ctx, id any) *MockRepositoryGetFormByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormByID", reflect.TypeOf((*MockRepository)(nil).GetFormByID), ctx, id)
	return &MockRepositoryGetFormByIDCall{Call: call}
}

// MockRepositoryGetFormByIDCall wrap *gomock.Call
type MockRepositoryGetFormByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetFormByIDCall) Return(arg0 *model.Form, arg1 error) *MockRepositoryGetFormByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetFormByIDCall) Do(f func(context.Context, string) (*model.Form, error)) *MockRepositoryGetFormByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetFormByIDCall) DoAndReturn(f func(context.Context, string) (*model.Form, error)) *MockRepositoryGetFormByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFormByPublicKey mocks base method.
func (m *MockRepository) GetFormByPublicKey(ctx context.Context, publicKey string) (*model.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormByPublicKey", ctx, publicKey)
	ret0, _ := ret[0].(*model.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormByPublicKey indicates an expected call of GetFormByPublicKey.
func (mr *MockRepositoryMockRecorder) GetFormByPublicKey(ctx, publicKey any) *MockRepositoryGetFormByPublicKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormByPublicKey", reflect.TypeOf((*MockRepository)(nil).GetFormByPublicKey), ctx, publicKey)
	return &MockRepositoryGetFormByPublicKeyCall{Call: call}
}

// MockRepositoryGetFormByPublicKeyCall wrap *gomock.Call
type MockRepositoryGetFormByPublicKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetFormByPublicKeyCall) Return(arg0 *model.Form, arg1 error) *MockRepositoryGetFormByPublicKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetFormByPublicKeyCall) Do(f func(context.Context, string) (*model.Form, error)) *MockRepositoryGetFormByPublicKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetFormByPublicKeyCall) DoAndReturn(f func(context.Context, string) (*model.Form, error)) *MockRepositoryGetFormByPublicKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFormsByStatus mocks base method.
func (m *MockRepository) GetFormsByStatus(ctx context.Context, status string) ([]*model.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFormsByStatus", ctx, status)
	ret0, _ := ret[0].([]*model.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFormsByStatus indicates an expected call of GetFormsByStatus.
func (mr *MockRepositoryMockRecorder) GetFormsByStatus(ctx, status any) *MockRepositoryGetFormsByStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFormsByStatus", reflect.TypeOf((*MockRepository)(nil).GetFormsByStatus), ctx, status)
	return &MockRepositoryGetFormsByStatusCall{Call: call}
}

// MockRepositoryGetFormsByStatusCall wrap *gomock.Call
type MockRepositoryGetFormsByStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetFormsByStatusCall) Return(arg0 []*model.Form, arg1 error) *MockRepositoryGetFormsByStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetFormsByStatusCall) Do(f func(context.Context, string) ([]*model.Form, error)) *MockRepositoryGetFormsByStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetFormsByStatusCall) DoAndReturn(f func(context.Context, string) ([]*model.Form, error)) *MockRepositoryGetFormsByStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPublishedSchemaVersion mocks base method.
func (m *MockRepository) GetPublishedSchemaVersion(ctx context.Context, publicKey string, version int) (*model.Form, *model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedSchemaVersion", ctx, publicKey, version)
	ret0, _ := ret[0].(*model.Form)
	ret1, _ := ret[1].(*model.SchemaVersion)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPublishedSchemaVersion indicates an expected call of GetPublishedSchemaVersion.
func (mr *MockRepositoryMockRecorder) GetPublishedSchemaVersion(ctx, publicKey, version any) *MockRepositoryGetPublishedSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedSchemaVersion", reflect.TypeOf((*MockRepository)(nil).GetPublishedSchemaVersion), ctx, publicKey, version)
	return &MockRepositoryGetPublishedSchemaVersionCall{Call: call}
}

// MockRepositoryGetPublishedSchemaVersionCall wrap *gomock.Call
type MockRepositoryGetPublishedSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetPublishedSchemaVersionCall) Return(arg0 *model.Form, arg1 *model.SchemaVersion, arg2 error) *MockRepositoryGetPublishedSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetPublishedSchemaVersionCall) Do(f func(context.Context, string, int) (*model.Form, *model.SchemaVersion, error)) *MockRepositoryGetPublishedSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetPublishedSchemaVersionCall) DoAndReturn(f func(context.Context, string, int) (*model.Form, *model.SchemaVersion, error)) *MockRepositoryGetPublishedSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSchemaVersion mocks base method.
func (m *MockRepository) GetSchemaVersion(ctx context.Context, formID string, version int) (*model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemaVersion", ctx, formID, version)
	ret0, _ := ret[0].(*model.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchemaVersion indicates an expected call of GetSchemaVersion.
func (mr *MockRepositoryMockRecorder) GetSchemaVersion(ctx, formID, version any) *MockRepositoryGetSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemaVersion", reflect.TypeOf((*MockRepository)(nil).GetSchemaVersion), ctx, formID, version)
	return &MockRepositoryGetSchemaVersionCall{Call: call}
}

// MockRepositoryGetSchemaVersionCall wrap *gomock.Call
type MockRepositoryGetSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSchemaVersionCall) Return(arg0 *model.SchemaVersion, arg1 error) *MockRepositoryGetSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSchemaVersionCall) Do(f func(context.Context, string, int) (*model.SchemaVersion, error)) *MockRepositoryGetSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSchemaVersionCall) DoAndReturn(f func(context.Context, string, int) (*model.SchemaVersion, error)) *MockRepositoryGetSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSubmissionByID mocks base method.
func (m *MockRepository) GetSubmissionByID(ctx context.Context, id string) (*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionByID", ctx, id)
	ret0, _ := ret[0].(*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionByID indicates an expected call of GetSubmissionByID.
func (mr *MockRepositoryMockRecorder) GetSubmissionByID(ctx, id any) *MockRepositoryGetSubmissionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionByID", reflect.TypeOf((*MockRepository)(nil).GetSubmissionByID), ctx, id)
	return &MockRepositoryGetSubmissionByIDCall{Call: call}
}

// MockRepositoryGetSubmissionByIDCall wrap *gomock.Call
type MockRepositoryGetSubmissionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSubmissionByIDCall) Return(arg0 *model.FormSubmission, arg1 error) *MockRepositoryGetSubmissionByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSubmissionByIDCall) Do(f func(context.Context, string) (*model.FormSubmission, error)) *MockRepositoryGetSubmissionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSubmissionByIDCall) DoAndReturn(f func(context.Context, string) (*model.FormSubmission, error)) *MockRepositoryGetSubmissionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSubmissionsByStatus mocks base method.
func (m *MockRepository) GetSubmissionsByStatus(ctx context.Context, status model.SubmissionStatus) ([]*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionsByStatus", ctx, status)
	ret0, _ := ret[0].([]*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionsByStatus indicates an expected call of GetSubmissionsByStatus.
func (mr *MockRepositoryMockRecorder) GetSubmissionsByStatus(ctx, status any) *MockRepositoryGetSubmissionsByStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionsByStatus", reflect.TypeOf((*MockRepository)(nil).GetSubmissionsByStatus), ctx, status)
	return &MockRepositoryGetSubmissionsByStatusCall{Call: call}
}

// MockRepositoryGetSubmissionsByStatusCall wrap *gomock.Call
type MockRepositoryGetSubmissionsByStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetSubmissionsByStatusCall) Return(arg0 []*model.FormSubmission, arg1 error) *MockRepositoryGetSubmissionsByStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetSubmissionsByStatusCall) Do(f func(context.Context, model.SubmissionStatus) ([]*model.FormSubmission, error)) *MockRepositoryGetSubmissionsByStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetSubmissionsByStatusCall) DoAndReturn(f func(context.Context, model.SubmissionStatus) ([]*model.FormSubmission, error)) *MockRepositoryGetSubmissionsByStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListForms mocks base method.
func (m *MockRepository) ListForms(ctx context.Context, userID string) ([]*model.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForms", ctx, userID)
	ret0, _ := ret[0].([]*model.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForms indicates an expected call of ListForms.
func (mr *MockRepositoryMockRecorder) ListForms(ctx, userID any) *MockRepositoryListFormsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForms", reflect.TypeOf((*MockRepository)(nil).ListForms), ctx, userID)
	return &MockRepositoryListFormsCall{Call: call}
}

// MockRepositoryListFormsCall wrap *gomock.Call
type MockRepositoryListFormsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListFormsCall) Return(arg0 []*model.Form, arg1 error) *MockRepositoryListFormsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListFormsCall) Do(f func(context.Context, string) ([]*model.Form, error)) *MockRepositoryListFormsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListFormsCall) DoAndReturn(f func(context.Context, string) ([]*model.Form, error)) *MockRepositoryListFormsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSubmissions mocks base method.
func (m *MockRepository) ListSubmissions(ctx context.Context, formID string) ([]*model.FormSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubmissions", ctx, formID)
	ret0, _ := ret[0].([]*model.FormSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubmissions indicates an expected call of ListSubmissions.
func (mr *MockRepositoryMockRecorder) ListSubmissions(ctx, formID any) *MockRepositoryListSubmissionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubmissions", reflect.TypeOf((*MockRepository)(nil).ListSubmissions), ctx, formID)
	return &MockRepositoryListSubmissionsCall{Call: call}
}

// MockRepositoryListSubmissionsCall wrap *gomock.Call
type MockRepositoryListSubmissionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListSubmissionsCall) Return(arg0 []*model.FormSubmission, arg1 error) *MockRepositoryListSubmissionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListSubmissionsCall) Do(f func(context.Context, string) ([]*model.FormSubmission, error)) *MockRepositoryListSubmissionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListSubmissionsCall) DoAndReturn(f func(context.Context, string) ([]*model.FormSubmission, error)) *MockRepositoryListSubmissionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSubmissionsPage mocks base method.
func (m *MockRepository) ListSubmissionsPage(ctx context.Context, formID string, before time.Time, beforeID string, limit int) ([]*model.FormSubmission, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubmissionsPage", ctx, formID, before, beforeID, limit)
	ret0, _ := ret[0].([]*model.FormSubmission)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSubmissionsPage indicates an expected call of ListSubmissionsPage.
func (mr *MockRepositoryMockRecorder) ListSubmissionsPage(ctx, formID, before, beforeID, limit any) *MockRepositoryListSubmissionsPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubmissionsPage", reflect.TypeOf((*MockRepository)(nil).ListSubmissionsPage), ctx, formID, before, beforeID, limit)
	return &MockRepositoryListSubmissionsPageCall{Call: call}
}

// MockRepositoryListSubmissionsPageCall wrap *gomock.Call
type MockRepositoryListSubmissionsPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListSubmissionsPageCall) Return(arg0 []*model.FormSubmission, arg1 bool, arg2 error) *MockRepositoryListSubmissionsPageCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListSubmissionsPageCall) Do(f func(context.Context, string, time.Time, string, int) ([]*model.FormSubmission, bool, error)) *MockRepositoryListSubmissionsPageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListSubmissionsPageCall) DoAndReturn(f func(context.Context, string, time.Time, string, int) ([]*model.FormSubmission, bool, error)) *MockRepositoryListSubmissionsPageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishSchemaVersion mocks base method.
func (m *MockRepository) PublishSchemaVersion(ctx context.Context, formID string, version int) (*model.SchemaVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSchemaVersion", ctx, formID, version)
	ret0, _ := ret[0].(*model.SchemaVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishSchemaVersion indicates an expected call of PublishSchemaVersion.
func (mr *MockRepositoryMockRecorder) PublishSchemaVersion(ctx, formID, version any) *MockRepositoryPublishSchemaVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSchemaVersion", reflect.TypeOf((*MockRepository)(nil).PublishSchemaVersion), ctx, formID, version)
	return &MockRepositoryPublishSchemaVersionCall{Call: call}
}

// MockRepositoryPublishSchemaVersionCall wrap *gomock.Call
type MockRepositoryPublishSchemaVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryPublishSchemaVersionCall) Return(arg0 *model.SchemaVersion, arg1 error) *MockRepositoryPublishSchemaVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryPublishSchemaVersionCall) Do(f func(context.Context, string, int) (*model.SchemaVersion, error)) *MockRepositoryPublishSchemaVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryPublishSchemaVersionCall) DoAndReturn(f func(context.Context, string, int) (*model.SchemaVersion, error)) *MockRepositoryPublishSchemaVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateForm mocks base method.
func (m *MockRepository) UpdateForm(ctx context.Context, form *model.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateForm", ctx, form)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateForm indicates an expected call of UpdateForm.
func (mr *MockRepositoryMockRecorder) UpdateForm(ctx, form any) *MockRepositoryUpdateFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateForm", reflect.TypeOf((*MockRepository)(nil).UpdateForm), ctx, form)
	return &MockRepositoryUpdateFormCall{Call: call}
}

// MockRepositoryUpdateFormCall wrap *gomock.Call
type MockRepositoryUpdateFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateFormCall) Return(arg0 error) *MockRepositoryUpdateFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateFormCall) Do(f func(context.Context, *model.Form) error) *MockRepositoryUpdateFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateFormCall) DoAndReturn(f func(context.Context, *model.Form) error) *MockRepositoryUpdateFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateSubmission mocks base method.
func (m *MockRepository) UpdateSubmission(ctx context.Context, submission *model.FormSubmission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubmission", ctx, submission)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubmission indicates an expected call of UpdateSubmission.
func (mr *MockRepositoryMockRecorder) UpdateSubmission(ctx, submission any) *MockRepositoryUpdateSubmissionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubmission", reflect.TypeOf((*MockRepository)(nil).UpdateSubmission), ctx, submission)
	return &MockRepositoryUpdateSubmissionCall{Call: call}
}

// MockRepositoryUpdateSubmissionCall wrap *gomock.Call
type MockRepositoryUpdateSubmissionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateSubmissionCall) Return(arg0 error) *MockRepositoryUpdateSubmissionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateSubmissionCall) Do(f func(context.Context, *model.FormSubmission) error) *MockRepositoryUpdateSubmissionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateSubmissionCall) DoAndReturn(f func(context.Context, *model.FormSubmission) error) *MockRepositoryUpdateSubmissionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
