// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -typed -source=interface.go -destination=../../../test/mocks/sanitization/mock_service.go -package=sanitization -mock_names=ServiceInterface=MockService
//

// Package sanitization is a generated GoMock package.
package sanitization

import (
	reflect "reflect"

	sanitization "github.com/goformx/goforms/internal/infrastructure/sanitization"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of ServiceInterface interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Alpha mocks base method.
func (m *MockService) Alpha(input string, spaces bool) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Alpha", input, spaces)
	ret0, _ := ret[0].(string)
	return ret0
}

// Alpha indicates an expected call of Alpha.
func (mr *MockServiceMockRecorder) Alpha(input, spaces any) *MockServiceAlphaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Alpha", reflect.TypeOf((*MockService)(nil).Alpha), input, spaces)
	return &MockServiceAlphaCall{Call: call}
}

// MockServiceAlphaCall wrap *gomock.Call
type MockServiceAlphaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAlphaCall) Return(arg0 string) *MockServiceAlphaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAlphaCall) Do(f func(string, bool) string) *MockServiceAlphaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAlphaCall) DoAndReturn(f func(string, bool) string) *MockServiceAlphaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AlphaNumeric mocks base method.
func (m *MockService) AlphaNumeric(input string, spaces bool) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlphaNumeric", input, spaces)
	ret0, _ := ret[0].(string)
	return ret0
}

// AlphaNumeric indicates an expected call of AlphaNumeric.
func (mr *MockServiceMockRecorder) AlphaNumeric(input, spaces any) *MockServiceAlphaNumericCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlphaNumeric", reflect.TypeOf((*MockService)(nil).AlphaNumeric), input, spaces)
	return &MockServiceAlphaNumericCall{Call: call}
}

// MockServiceAlphaNumericCall wrap *gomock.Call
type MockServiceAlphaNumericCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAlphaNumericCall) Return(arg0 string) *MockServiceAlphaNumericCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAlphaNumericCall) Do(f func(string, bool) string) *MockServiceAlphaNumericCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAlphaNumericCall) DoAndReturn(f func(string, bool) string) *MockServiceAlphaNumericCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Domain mocks base method.
func (m *MockService) Domain(input string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Domain", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Domain indicates an expected call of Domain.
func (mr *MockServiceMockRecorder) Domain(input any) *MockServiceDomainCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Domain", reflect.TypeOf((*MockService)(nil).Domain), input)
	return &MockServiceDomainCall{Call: call}
}

// MockServiceDomainCall wrap *gomock.Call
type MockServiceDomainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDomainCall) Return(arg0 string, arg1 error) *MockServiceDomainCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDomainCall) Do(f func(string) (string, error)) *MockServiceDomainCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDomainCall) DoAndReturn(f func(string) (string, error)) *MockServiceDomainCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Email mocks base method.
func (m *MockService) Email(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockServiceMockRecorder) Email(input any) *MockServiceEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockService)(nil).Email), input)
	return &MockServiceEmailCall{Call: call}
}

// MockServiceEmailCall wrap *gomock.Call
type MockServiceEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEmailCall) Return(arg0 string) *MockServiceEmailCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEmailCall) Do(f func(string) string) *MockServiceEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEmailCall) DoAndReturn(f func(string) string) *MockServiceEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HTML mocks base method.
func (m *MockService) HTML(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTML", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// HTML indicates an expected call of HTML.
func (mr *MockServiceMockRecorder) HTML(input any) *MockServiceHTMLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTML", reflect.TypeOf((*MockService)(nil).HTML), input)
	return &MockServiceHTMLCall{Call: call}
}

// MockServiceHTMLCall wrap *gomock.Call
type MockServiceHTMLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceHTMLCall) Return(arg0 string) *MockServiceHTMLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceHTMLCall) Do(f func(string) string) *MockServiceHTMLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceHTMLCall) DoAndReturn(f func(string) string) *MockServiceHTMLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IPAddress mocks base method.
func (m *MockService) IPAddress(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IPAddress", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// IPAddress indicates an expected call of IPAddress.
func (mr *MockServiceMockRecorder) IPAddress(input any) *MockServiceIPAddressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IPAddress", reflect.TypeOf((*MockService)(nil).IPAddress), input)
	return &MockServiceIPAddressCall{Call: call}
}

// MockServiceIPAddressCall wrap *gomock.Call
type MockServiceIPAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceIPAddressCall) Return(arg0 string) *MockServiceIPAddressCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceIPAddressCall) Do(f func(string) string) *MockServiceIPAddressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceIPAddressCall) DoAndReturn(f func(string) string) *MockServiceIPAddressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Numeric mocks base method.
func (m *MockService) Numeric(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Numeric", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// Numeric indicates an expected call of Numeric.
func (mr *MockServiceMockRecorder) Numeric(input any) *MockServiceNumericCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Numeric", reflect.TypeOf((*MockService)(nil).Numeric), input)
	return &MockServiceNumericCall{Call: call}
}

// MockServiceNumericCall wrap *gomock.Call
type MockServiceNumericCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceNumericCall) Return(arg0 string) *MockServiceNumericCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceNumericCall) Do(f func(string) string) *MockServiceNumericCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceNumericCall) DoAndReturn(f func(string) string) *MockServiceNumericCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Path mocks base method.
func (m *MockService) Path(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockServiceMockRecorder) Path(input any) *MockServicePathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockService)(nil).Path), input)
	return &MockServicePathCall{Call: call}
}

// MockServicePathCall wrap *gomock.Call
type MockServicePathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServicePathCall) Return(arg0 string) *MockServicePathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServicePathCall) Do(f func(string) string) *MockServicePathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServicePathCall) DoAndReturn(f func(string) string) *MockServicePathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeForLogging mocks base method.
func (m *MockService) SanitizeForLogging(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeForLogging", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// SanitizeForLogging indicates an expected call of SanitizeForLogging.
func (mr *MockServiceMockRecorder) SanitizeForLogging(input any) *MockServiceSanitizeForLoggingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeForLogging", reflect.TypeOf((*MockService)(nil).SanitizeForLogging), input)
	return &MockServiceSanitizeForLoggingCall{Call: call}
}

// MockServiceSanitizeForLoggingCall wrap *gomock.Call
type MockServiceSanitizeForLoggingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSanitizeForLoggingCall) Return(arg0 string) *MockServiceSanitizeForLoggingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSanitizeForLoggingCall) Do(f func(string) string) *MockServiceSanitizeForLoggingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSanitizeForLoggingCall) DoAndReturn(f func(string) string) *MockServiceSanitizeForLoggingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeFormData mocks base method.
func (m *MockService) SanitizeFormData(data, fieldTypes map[string]string) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeFormData", data, fieldTypes)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// SanitizeFormData indicates an expected call of SanitizeFormData.
func (mr *MockServiceMockRecorder) SanitizeFormData(data, fieldTypes any) *MockServiceSanitizeFormDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeFormData", reflect.TypeOf((*MockService)(nil).SanitizeFormData), data, fieldTypes)
	return &MockServiceSanitizeFormDataCall{Call: call}
}

// MockServiceSanitizeFormDataCall wrap *gomock.Call
type MockServiceSanitizeFormDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSanitizeFormDataCall) Return(arg0 map[string]string) *MockServiceSanitizeFormDataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSanitizeFormDataCall) Do(f func(map[string]string, map[string]string) map[string]string) *MockServiceSanitizeFormDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSanitizeFormDataCall) DoAndReturn(f func(map[string]string, map[string]string) map[string]string) *MockServiceSanitizeFormDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeJSON mocks base method.
func (m *MockService) SanitizeJSON(data any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeJSON", data)
	ret0, _ := ret[0].(any)
	return ret0
}

// SanitizeJSON indicates an expected call of SanitizeJSON.
func (mr *MockServiceMockRecorder) SanitizeJSON(data any) *MockServiceSanitizeJSONCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeJSON", reflect.TypeOf((*MockService)(nil).SanitizeJSON), data)
	return &MockServiceSanitizeJSONCall{Call: call}
}

// MockServiceSanitizeJSONCall wrap *gomock.Call
type MockServiceSanitizeJSONCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSanitizeJSONCall) Return(arg0 any) *MockServiceSanitizeJSONCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSanitizeJSONCall) Do(f func(any) any) *MockServiceSanitizeJSONCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSanitizeJSONCall) DoAndReturn(f func(any) any) *MockServiceSanitizeJSONCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeMap mocks base method.
func (m *MockService) SanitizeMap(data map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SanitizeMap", data)
}

// SanitizeMap indicates an expected call of SanitizeMap.
func (mr *MockServiceMockRecorder) SanitizeMap(data any) *MockServiceSanitizeMapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeMap", reflect.TypeOf((*MockService)(nil).SanitizeMap), data)
	return &MockServiceSanitizeMapCall{Call: call}
}

// MockServiceSanitizeMapCall wrap *gomock.Call
type MockServiceSanitizeMapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSanitizeMapCall) Return() *MockServiceSanitizeMapCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSanitizeMapCall) Do(f func(map[string]any)) *MockServiceSanitizeMapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSanitizeMapCall) DoAndReturn(f func(map[string]any)) *MockServiceSanitizeMapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeSlice mocks base method.
func (m *MockService) SanitizeSlice(data []any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SanitizeSlice", data)
}

// SanitizeSlice indicates an expected call of SanitizeSlice.
func (mr *MockServiceMockRecorder) SanitizeSlice(data any) *MockServiceSanitizeSliceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeSlice", reflect.TypeOf((*MockService)(nil).SanitizeSlice), data)
	return &MockServiceSanitizeSliceCall{Call: call}
}

// MockServiceSanitizeSliceCall wrap *gomock.Call
type MockServiceSanitizeSliceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSanitizeSliceCall) Return() *MockServiceSanitizeSliceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSanitizeSliceCall) Do(f func([]any)) *MockServiceSanitizeSliceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSanitizeSliceCall) DoAndReturn(f func([]any)) *MockServiceSanitizeSliceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeStruct mocks base method.
func (m *MockService) SanitizeStruct(obj any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SanitizeStruct", obj)
}

// SanitizeStruct indicates an expected call of SanitizeStruct.
func (mr *MockServiceMockRecorder) SanitizeStruct(obj any) *MockServiceSanitizeStructCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeStruct", reflect.TypeOf((*MockService)(nil).SanitizeStruct), obj)
	return &MockServiceSanitizeStructCall{Call: call}
}

// MockServiceSanitizeStructCall wrap *gomock.Call
type MockServiceSanitizeStructCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSanitizeStructCall) Return() *MockServiceSanitizeStructCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSanitizeStructCall) Do(f func(any)) *MockServiceSanitizeStructCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSanitizeStructCall) DoAndReturn(f func(any)) *MockServiceSanitizeStructCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SanitizeWithOptions mocks base method.
func (m *MockService) SanitizeWithOptions(input string, opts sanitization.SanitizeOptions) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeWithOptions", input, opts)
	ret0, _ := ret[0].(string)
	return ret0
}

// SanitizeWithOptions indicates an expected call of SanitizeWithOptions.
func (mr *MockServiceMockRecorder) SanitizeWithOptions(input, opts any) *MockServiceSanitizeWithOptionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeWithOptions", reflect.TypeOf((*MockService)(nil).SanitizeWithOptions), input, opts)
	return &MockServiceSanitizeWithOptionsCall{Call: call}
}

// MockServiceSanitizeWithOptionsCall wrap *gomock.Call
type MockServiceSanitizeWithOptionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSanitizeWithOptionsCall) Return(arg0 string) *MockServiceSanitizeWithOptionsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSanitizeWithOptionsCall) Do(f func(string, sanitization.SanitizeOptions) string) *MockServiceSanitizeWithOptionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSanitizeWithOptionsCall) DoAndReturn(f func(string, sanitization.SanitizeOptions) string) *MockServiceSanitizeWithOptionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Scripts mocks base method.
func (m *MockService) Scripts(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scripts", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// Scripts indicates an expected call of Scripts.
func (mr *MockServiceMockRecorder) Scripts(input any) *MockServiceScriptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scripts", reflect.TypeOf((*MockService)(nil).Scripts), input)
	return &MockServiceScriptsCall{Call: call}
}

// MockServiceScriptsCall wrap *gomock.Call
type MockServiceScriptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceScriptsCall) Return(arg0 string) *MockServiceScriptsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceScriptsCall) Do(f func(string) string) *MockServiceScriptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceScriptsCall) DoAndReturn(f func(string) string) *MockServiceScriptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SingleLine mocks base method.
func (m *MockService) SingleLine(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SingleLine", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// SingleLine indicates an expected call of SingleLine.
func (mr *MockServiceMockRecorder) SingleLine(input any) *MockServiceSingleLineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SingleLine", reflect.TypeOf((*MockService)(nil).SingleLine), input)
	return &MockServiceSingleLineCall{Call: call}
}

// MockServiceSingleLineCall wrap *gomock.Call
type MockServiceSingleLineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSingleLineCall) Return(arg0 string) *MockServiceSingleLineCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSingleLineCall) Do(f func(string) string) *MockServiceSingleLineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSingleLineCall) DoAndReturn(f func(string) string) *MockServiceSingleLineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// String mocks base method.
func (m *MockService) String(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockServiceMockRecorder) String(input any) *MockServiceStringCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockService)(nil).String), input)
	return &MockServiceStringCall{Call: call}
}

// MockServiceStringCall wrap *gomock.Call
type MockServiceStringCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceStringCall) Return(arg0 string) *MockServiceStringCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceStringCall) Do(f func(string) string) *MockServiceStringCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceStringCall) DoAndReturn(f func(string) string) *MockServiceStringCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TrimAndSanitize mocks base method.
func (m *MockService) TrimAndSanitize(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrimAndSanitize", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// TrimAndSanitize indicates an expected call of TrimAndSanitize.
func (mr *MockServiceMockRecorder) TrimAndSanitize(input any) *MockServiceTrimAndSanitizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrimAndSanitize", reflect.TypeOf((*MockService)(nil).TrimAndSanitize), input)
	return &MockServiceTrimAndSanitizeCall{Call: call}
}

// MockServiceTrimAndSanitizeCall wrap *gomock.Call
type MockServiceTrimAndSanitizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTrimAndSanitizeCall) Return(arg0 string) *MockServiceTrimAndSanitizeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTrimAndSanitizeCall) Do(f func(string) string) *MockServiceTrimAndSanitizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTrimAndSanitizeCall) DoAndReturn(f func(string) string) *MockServiceTrimAndSanitizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TrimAndSanitizeEmail mocks base method.
func (m *MockService) TrimAndSanitizeEmail(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrimAndSanitizeEmail", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// TrimAndSanitizeEmail indicates an expected call of TrimAndSanitizeEmail.
func (mr *MockServiceMockRecorder) TrimAndSanitizeEmail(input any) *MockServiceTrimAndSanitizeEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrimAndSanitizeEmail", reflect.TypeOf((*MockService)(nil).TrimAndSanitizeEmail), input)
	return &MockServiceTrimAndSanitizeEmailCall{Call: call}
}

// MockServiceTrimAndSanitizeEmailCall wrap *gomock.Call
type MockServiceTrimAndSanitizeEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTrimAndSanitizeEmailCall) Return(arg0 string) *MockServiceTrimAndSanitizeEmailCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTrimAndSanitizeEmailCall) Do(f func(string) string) *MockServiceTrimAndSanitizeEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTrimAndSanitizeEmailCall) DoAndReturn(f func(string) string) *MockServiceTrimAndSanitizeEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// URI mocks base method.
func (m *MockService) URI(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URI", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// URI indicates an expected call of URI.
func (mr *MockServiceMockRecorder) URI(input any) *MockServiceURICall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URI", reflect.TypeOf((*MockService)(nil).URI), input)
	return &MockServiceURICall{Call: call}
}

// MockServiceURICall wrap *gomock.Call
type MockServiceURICall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceURICall) Return(arg0 string) *MockServiceURICall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceURICall) Do(f func(string) string) *MockServiceURICall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceURICall) DoAndReturn(f func(string) string) *MockServiceURICall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// URL mocks base method.
func (m *MockService) URL(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockServiceMockRecorder) URL(input any) *MockServiceURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockService)(nil).URL), input)
	return &MockServiceURLCall{Call: call}
}

// MockServiceURLCall wrap *gomock.Call
type MockServiceURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceURLCall) Return(arg0 string) *MockServiceURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceURLCall) Do(f func(string) string) *MockServiceURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceURLCall) DoAndReturn(f func(string) string) *MockServiceURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// XML mocks base method.
func (m *MockService) XML(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XML", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// XML indicates an expected call of XML.
func (mr *MockServiceMockRecorder) XML(input any) *MockServiceXMLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XML", reflect.TypeOf((*MockService)(nil).XML), input)
	return &MockServiceXMLCall{Call: call}
}

// MockServiceXMLCall wrap *gomock.Call
type MockServiceXMLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceXMLCall) Return(arg0 string) *MockServiceXMLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceXMLCall) Do(f func(string) string) *MockServiceXMLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceXMLCall) DoAndReturn(f func(string) string) *MockServiceXMLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
